import { GENERATIVE_PARTICLES_ANIMATABLE } from "../data/particlesDefaults";

// =============================================================================
// GENERATIVE ANIMATABLE REGISTRY — which config knobs may be driven per frame
// =============================================================================
//
// One table per generative family (particles now; effects and grids next), each
// keyed by the object's `config.type` and generated by the lab's gen.mjs from the
// component's own `applyConfig` source: a knob is listed only when applyConfig
// pushes it into a uniform, because that is the single call a per-frame override
// goes through. Structural knobs (they rebuild the simulation), mode selects and
// `size` (the object's transform) are never listed.
//
// Adding a family is a line in FAMILIES plus its generated table — the animations
// UI, getAnimatableProperties and the mouse-move system all read from here, so a
// new family cannot drift from what the renderer can actually apply.
//

export interface AnimatableConfigProperty {
    value: string;
    label: string;
}

export type GenerativeFamily = 'particles';

const FAMILIES: Record<GenerativeFamily, Record<string, AnimatableConfigProperty[]>> = {
    particles: GENERATIVE_PARTICLES_ANIMATABLE,
};

/** The animatable knobs of one generative object, by family and config.type. */
export function getGenerativeAnimatable(
    family: GenerativeFamily,
    config: { type?: string } | undefined | null,
): AnimatableConfigProperty[] {
    const table = FAMILIES[family];
    const type = config?.type;
    if (!table || !type) return [];
    return table[type] ? [...table[type]] : [];
}

/** True when this config belongs to the family (i.e. the registry knows its type). */
export function isGenerativeFamilyConfig(
    family: GenerativeFamily,
    config: { type?: string } | undefined | null,
): boolean {
    const type = config?.type;
    return !!type && !!FAMILIES[family]?.[type];
}
