import { GENERATIVE_PARTICLES_ANIMATABLE } from "../data/particlesDefaults";
import { LIGHTS_ANIMATABLE } from "../data/lightsDefaults";
import { EFFECTS_ANIMATABLE } from "../data/effectsDefaults";
import { GRIDS_ANIMATABLE } from "../data/gridsDefaults";
import { ENVIRONMENT_OBJECTS_ANIMATABLE } from "../data/environmentDefaults";
import { SPACE_OBJECTS_ANIMATABLE } from "../data/spaceDefaults";
import { LAND_OBJECTS_ANIMATABLE } from "../data/landDefaults";
import { TEXT_OBJECTS_ANIMATABLE } from "../data/textDefaults";

// =============================================================================
// GENERATIVE ANIMATABLE REGISTRY — which config knobs may be driven per frame
// =============================================================================
//
// One table per generative family (particles, effects, grids, plus lights), each
// keyed by the object's `config.type` and generated by the lab's gen.mjs from the
// component's own `applyConfig` source: a knob is listed only when applyConfig
// pushes it into a uniform, because that is the single call a per-frame override
// goes through. Structural knobs (they rebuild the simulation), mode selects and
// `size` (the object's transform) are never listed.
//
// Adding a family is a line in FAMILIES plus its generated table — the animations
// UI, getAnimatableProperties and the mouse-move system all read from here, so a
// new family cannot drift from what the renderer can actually apply.
//

export interface AnimatableConfigProperty {
    value: string;
    label: string;
}

export type GenerativeFamily = 'particles' | 'lights' | 'effects' | 'grids' | 'environment' | 'space' | 'land' | 'text';

// Partial: grids list only the types converted to the config pattern so far (effects list all).
const FAMILIES: Record<GenerativeFamily, Partial<Record<string, AnimatableConfigProperty[]>>> = {
    particles: GENERATIVE_PARTICLES_ANIMATABLE,
    // Lights are not generative, but they store their knobs in `config` and drive
    // them through one applyLightConfig per frame, so they use the same registry.
    lights: LIGHTS_ANIMATABLE,
    effects: EFFECTS_ANIMATABLE,
    grids: GRIDS_ANIMATABLE,
    // Weather objects (type 'environment'): snow… The legacy rain is not in this table.
    environment: ENVIRONMENT_OBJECTS_ANIMATABLE,
    // Celestial bodies and backdrops (type 'space'): stars, earth, solarSystem, shootingStars.
    space: SPACE_OBJECTS_ANIMATABLE,
    // Placeable patches of terrain (type 'land'): mountains, hills, dunes, canyon.
    land: LAND_OBJECTS_ANIMATABLE,
    // Animated text looks (type 'text', config.type set): handwriting, neonTube, fourierSketch. The legacy bitmap / 3D text is not in this table.
    text: TEXT_OBJECTS_ANIMATABLE,
};

/** The animatable knobs of one generative object, by family and config.type. */
export function getGenerativeAnimatable(
    family: GenerativeFamily,
    config: { type?: string } | undefined | null,
): AnimatableConfigProperty[] {
    const table = FAMILIES[family];
    const type = config?.type;
    if (!table || !type) return [];
    const list = table[type];
    return list ? [...list] : [];
}

/** True when this config belongs to the family (i.e. the registry knows its type). */
export function isGenerativeFamilyConfig(
    family: GenerativeFamily,
    config: { type?: string } | undefined | null,
): boolean {
    const type = config?.type;
    return !!type && !!FAMILIES[family]?.[type];
}
