export interface SandPreset {
    name: string;
    type: string;
    category: string;
    description: string;
    tags: string[];
    materialType: string;
    settings: Record<string, any>;
}
// NOTE: u_mouseStrength is intentionally omitted — it is ramped at runtime by
// <Sand interactive> as the cursor hovers, so presets shouldn't pin it.
export const sandPresets: SandPreset[] = [
    {
        name: "Sahara Dune",
        type: "sand",
        category: "surface",
        description: "Classic warm golden desert sand with wind-combed ripples slowly crawling downwind under a high, dry sun",
        tags: ["sand", "desert", "golden", "dune", "warm", "realistic"],
        materialType: "SandMaterial",
        settings: {
            u_time: 0,
            u_color: [0.80, 0.66, 0.43],
            u_colorVariation: 0.45,
            u_scale: 1.0,
            u_rippleScale: 0.9,
            u_rippleStrength: 1.1,
            u_rippleAsymmetry: 0.65,
            u_windDir: [1.0, 0.25],
            u_grainDensity: 1.0,
            u_roughness: 0.9,
            u_sunDirection: [0.45, 0.78, 0.30],
            u_sunColor: [1.0, 0.93, 0.80],
            u_sunIntensity: 1.0,
            u_ambient: 1.0,
            u_skyColor: [0.55, 0.68, 0.92],
            u_groundColor: [0.50, 0.36, 0.22],
            u_windSpeed: 0.18,
            u_mouseRadius: 3.5,
            u_mouseSwirl: 0.6,
        }
    },
    {
        name: "White Sands",
        type: "sand",
        category: "surface",
        description: "Luminous near-white gypsum dunes — bright, chalk-matte and almost glowing under a high sun and a strong sky bounce",
        tags: ["sand", "white", "gypsum", "bright", "luminous", "pale"],
        materialType: "SandMaterial",
        settings: {
            u_time: 0,
            u_color: [0.96, 0.95, 0.93],
            u_colorVariation: 0.15,
            u_scale: 1.2,
            u_rippleScale: 1.15,
            u_rippleStrength: 1.05,
            u_rippleAsymmetry: 0.58,
            u_windDir: [0.8, 0.6],
            u_grainDensity: 0.8,
            u_roughness: 0.95,
            u_sunDirection: [0.40, 0.85, 0.25],
            u_sunColor: [1.0, 0.99, 0.96],
            u_sunIntensity: 1.2,
            u_ambient: 1.3,
            u_skyColor: [0.62, 0.74, 0.97],
            u_groundColor: [0.78, 0.76, 0.72],
            u_windSpeed: 0.15,
            u_mouseRadius: 3.0,
            u_mouseSwirl: 0.5,
        }
    },
    {
        name: "Black Volcanic",
        type: "sand",
        category: "surface",
        description: "Near-black basalt beach sand that glitters hard — bright white glints scatter across the dark grains in low, raking light",
        tags: ["sand", "black", "volcanic", "basalt", "glitter", "contrast"],
        materialType: "SandMaterial",
        settings: {
            u_time: 0,
            u_color: [0.045, 0.043, 0.050],
            u_colorVariation: 0.45,
            u_scale: 1.35,
            u_rippleScale: 1.05,
            u_rippleStrength: 1.05,
            u_rippleAsymmetry: 0.6,
            u_windDir: [1.0, 0.1],
            u_grainDensity: 1.9,
            u_roughness: 0.55,
            u_sunDirection: [0.72, 0.42, 0.55],
            u_sunColor: [1.0, 0.97, 0.90],
            u_sunIntensity: 1.2,
            u_ambient: 0.6,
            u_skyColor: [0.45, 0.58, 0.82],
            u_groundColor: [0.08, 0.08, 0.10],
            u_windSpeed: 0.12,
            u_mouseRadius: 3.0,
            u_mouseSwirl: 0.6,
        }
    },
    {
        name: "Red Outback",
        type: "sand",
        category: "surface",
        description: "Deep iron-oxide red desert sand, rich and rusty, with steep wind-driven slip faces",
        tags: ["sand", "red", "outback", "iron", "rust", "warm"],
        materialType: "SandMaterial",
        settings: {
            u_time: 0,
            u_color: [0.62, 0.26, 0.13],
            u_colorVariation: 0.60,
            u_scale: 0.95,
            u_rippleScale: 0.85,
            u_rippleStrength: 1.25,
            u_rippleAsymmetry: 0.72,
            u_windDir: [1.0, 0.35],
            u_grainDensity: 1.0,
            u_roughness: 0.9,
            u_sunDirection: [0.45, 0.62, 0.45],
            u_sunColor: [1.0, 0.85, 0.60],
            u_sunIntensity: 1.05,
            u_ambient: 1.0,
            u_skyColor: [0.55, 0.60, 0.82],
            u_groundColor: [0.45, 0.20, 0.10],
            u_windSpeed: 0.16,
            u_mouseRadius: 3.0,
            u_mouseSwirl: 0.6,
        }
    },
    {
        name: "Pink Coral",
        type: "sand",
        category: "surface",
        description: "Soft blush-pink shell sand from crushed coral, calm and fine with a gentle shell-grit shimmer",
        tags: ["sand", "pink", "coral", "beach", "tropical", "soft"],
        materialType: "SandMaterial",
        settings: {
            u_time: 0,
            u_color: [0.92, 0.74, 0.70],
            u_colorVariation: 0.40,
            u_scale: 1.15,
            u_rippleScale: 1.0,
            u_rippleStrength: 0.8,
            u_rippleAsymmetry: 0.55,
            u_windDir: [0.6, 0.8],
            u_grainDensity: 1.1,
            u_roughness: 0.85,
            u_sunDirection: [0.50, 0.80, 0.30],
            u_sunColor: [1.0, 0.95, 0.88],
            u_sunIntensity: 1.0,
            u_ambient: 1.1,
            u_skyColor: [0.50, 0.70, 0.95],
            u_groundColor: [0.60, 0.40, 0.40],
            u_windSpeed: 0.10,
            u_mouseRadius: 3.0,
            u_mouseSwirl: 0.45,
        }
    },
    {
        name: "Martian Regolith",
        type: "sand",
        category: "surface",
        description: "Dusty rust-brown Martian fines under a butterscotch sky — matte, long-wavelength ripples, weak distant sun",
        tags: ["sand", "mars", "regolith", "dust", "sci-fi", "rust"],
        materialType: "SandMaterial",
        settings: {
            u_time: 0,
            u_color: [0.55, 0.32, 0.22],
            u_colorVariation: 0.45,
            u_scale: 1.1,
            u_rippleScale: 0.65,
            u_rippleStrength: 0.9,
            u_rippleAsymmetry: 0.75,
            u_windDir: [1.0, 0.2],
            u_grainDensity: 0.6,
            u_roughness: 0.95,
            u_sunDirection: [0.6, 0.55, 0.35],
            u_sunColor: [1.0, 0.90, 0.78],
            u_sunIntensity: 0.85,
            u_ambient: 0.85,
            u_skyColor: [0.78, 0.62, 0.45],
            u_groundColor: [0.40, 0.22, 0.14],
            u_windSpeed: 0.10,
            u_mouseRadius: 3.5,
            u_mouseSwirl: 0.5,
        }
    },
    {
        name: "Lunar Regolith",
        type: "sand",
        category: "surface",
        description: "Gray Moon dust with no air to soften it — harsh white sun, near-black sky, a faint glassy sparkle and dead-still ripples",
        tags: ["sand", "moon", "regolith", "gray", "space", "dramatic"],
        materialType: "SandMaterial",
        settings: {
            u_time: 0,
            u_color: [0.32, 0.31, 0.30],
            u_colorVariation: 0.30,
            u_scale: 1.25,
            u_rippleScale: 1.0,
            u_rippleStrength: 0.2,
            u_rippleAsymmetry: 0.5,
            u_windDir: [1.0, 0.0],
            u_grainDensity: 0.9,
            u_roughness: 0.96,
            u_sunDirection: [0.85, 0.40, 0.30],
            u_sunColor: [1.0, 0.99, 0.96],
            u_sunIntensity: 1.3,
            u_ambient: 0.12,
            u_skyColor: [0.02, 0.02, 0.03],
            u_groundColor: [0.18, 0.18, 0.18],
            u_windSpeed: 0.0,
            u_mouseRadius: 3.0,
            u_mouseSwirl: 0.3,
        }
    },
    {
        name: "Wet Shore",
        type: "sand",
        category: "surface",
        description: "Damp, packed beach sand at golden hour — darker, glossier, fine wave-ripples and bright quartz glints",
        tags: ["sand", "beach", "wet", "golden-hour", "shore", "glossy"],
        materialType: "SandMaterial",
        settings: {
            u_time: 0,
            u_color: [0.60, 0.49, 0.35],
            u_colorVariation: 0.35,
            u_scale: 1.2,
            u_rippleScale: 1.3,
            u_rippleStrength: 0.55,
            u_rippleAsymmetry: 0.5,
            u_windDir: [0.3, 1.0],
            u_grainDensity: 1.2,
            u_roughness: 0.55,
            u_sunDirection: [0.75, 0.32, 0.55],
            u_sunColor: [1.0, 0.80, 0.55],
            u_sunIntensity: 1.1,
            u_ambient: 0.95,
            u_skyColor: [0.65, 0.60, 0.70],
            u_groundColor: [0.40, 0.30, 0.22],
            u_windSpeed: 0.07,
            u_mouseRadius: 2.8,
            u_mouseSwirl: 0.4,
        }
    },
    {
        name: "Dune Sea Dusk",
        type: "sand",
        category: "surface",
        description: "Tall dunes raked low by a deep-orange dusk sun, long shadows in the troughs and ripples streaming on a strong wind",
        tags: ["sand", "dusk", "dune", "sunset", "atmospheric", "warm"],
        materialType: "SandMaterial",
        settings: {
            u_time: 0,
            u_color: [0.66, 0.50, 0.42],
            u_colorVariation: 0.50,
            u_scale: 0.9,
            u_rippleScale: 0.8,
            u_rippleStrength: 1.3,
            u_rippleAsymmetry: 0.7,
            u_windDir: [1.0, 0.4],
            u_grainDensity: 1.0,
            u_roughness: 0.9,
            u_sunDirection: [0.92, 0.16, 0.30],
            u_sunColor: [1.0, 0.55, 0.30],
            u_sunIntensity: 1.2,
            u_ambient: 0.7,
            u_skyColor: [0.40, 0.40, 0.60],
            u_groundColor: [0.35, 0.20, 0.18],
            u_windSpeed: 0.22,
            u_mouseRadius: 4.0,
            u_mouseSwirl: 0.7,
        }
    },
    {
        name: "Zen Garden",
        type: "sand",
        category: "surface",
        description: "Pale raked karesansui sand with deep, regular parallel grooves held perfectly still under a calm, even light",
        tags: ["sand", "zen", "raked", "japanese", "stylized", "calm"],
        materialType: "SandMaterial",
        settings: {
            u_time: 0,
            u_color: [0.86, 0.83, 0.76],
            u_colorVariation: 0.20,
            u_scale: 0.9,
            u_rippleScale: 1.6,
            u_rippleStrength: 1.6,
            u_rippleAsymmetry: 0.5,
            u_windDir: [1.0, 0.0],
            u_grainDensity: 0.8,
            u_roughness: 0.92,
            u_sunDirection: [0.40, 0.80, 0.35],
            u_sunColor: [1.0, 0.96, 0.90],
            u_sunIntensity: 0.95,
            u_ambient: 1.15,
            u_skyColor: [0.60, 0.70, 0.90],
            u_groundColor: [0.60, 0.56, 0.50],
            u_windSpeed: 0.0,
            u_mouseRadius: 2.5,
            u_mouseSwirl: 0.2,
        }
    }
];
