// Property table (moved from the client). The registry (../registry.ts) is built on these tables.
import type { OptionalProperty } from './optionalProperties';
import type { GenerativeParticlesType } from '../../types/generativeParticles';

// =============================================================================
// GENERATIVE PARTICLES OPTIONAL PROPERTIES
// The configurable inputs for each generative particle object (type 'particles').
// Order: base, variant, mouse (pointer*), trails (trail*). Selects carry optionLabels.
// =============================================================================

export const tidalStreamParticlesProperties: OptionalProperty[] = [
  { name: 'intensity', description: 'Overall brightness', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'speed', description: 'Simulation time scale', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'opacity', description: 'Overall opacity', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'size', description: 'World size of the object (units)', type: 'number', min: 0.2, max: 4, step: 0.01 },
  { name: 'color', description: 'Blue-shift tint (stars moving toward the camera)', type: 'color' },
  { name: 'particleCount', description: 'Stars in the satellites and their streams (CPU simulated)', type: 'number', min: 3000, max: 40000, step: 1000 },
  { name: 'satelliteCount', description: 'Dwarf galaxies being torn apart: arcs, radial shells, a polar ring', type: 'number', min: 1, max: 3, step: 1 },
  { name: 'satelliteMass', description: 'Dwarf mass: heavier dwarfs hold their stars longer', type: 'number', min: 0.0001, max: 0.003, step: 0.0001 },
  { name: 'orbitEccentricity', description: 'Elongation of the main dwarf’s orbit (the others are set relative to it)', type: 'number', min: 0, max: 0.8, step: 0.01 },
  { name: 'streamAge', description: 'Orbits already completed when the object appears', type: 'number', min: 0, max: 5, step: 0.1 },
  { name: 'dopplerScale', description: 'Strength of the Doppler shift', type: 'number', min: 0, max: 6, step: 0.1 },
  { name: 'redshiftColor', description: 'Red-shift tint (stars moving away from the camera)', type: 'color' },
  { name: 'discStars', description: 'Stars in the host spiral galaxy (GPU, analytic)', type: 'number', min: 0, max: 200000, step: 5000 },
  { name: 'armCount', description: 'Spiral arms of the density wave', type: 'number', min: 1, max: 4, step: 1 },
  { name: 'nebulaColor', description: 'Emission nebulae along the arm crests (H-alpha)', type: 'color' },
  { name: 'starSize', description: 'Star sprite size', type: 'number', min: 0.2, max: 3, step: 0.01 },
  { name: 'pointerMode', description: 'What the cursor is: off, a dark subhalo, a spinning black hole, or a spectroscope loupe', type: 'select', options: ['none', 'subhalo', 'blackHole', 'spectroscope'], optionLabels: ['Off', 'Dark subhalo', 'Spinning black hole', 'Spectroscope'] },
  { name: 'pointerStrength', description: 'Mass / spin / magnification of the cursor (0 = no interaction)', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'pointerRadius', description: 'Einstein radius, horizon size or loupe size', type: 'number', min: 0.2, max: 3, step: 0.01 },
  { name: 'pointerColor', description: 'Colour of the photon ring / loupe reticle', type: 'color' },
  { name: 'trailMode', description: 'Long exposure, comet tails or stardust afterglow', type: 'select', options: ['none', 'streak', 'comet', 'echo'], optionLabels: ['Off', 'Long exposure', 'Comet tails', 'Stardust'] },
  { name: 'trailLength', description: 'Trail duration in seconds', type: 'number', min: 0.2, max: 6, step: 0.05 },
  { name: 'trailOpacity', description: 'Trail brightness', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'trailColor', description: 'Colour trails cool toward', type: 'color' },
  { name: 'trailShare', description: 'Fraction of stars that leave trails', type: 'number', min: 0.02, max: 1, step: 0.01 },
];

export const brownianDustParticlesProperties: OptionalProperty[] = [
  { name: 'intensity', description: 'Overall brightness', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'speed', description: 'Simulation time scale', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'opacity', description: 'Overall opacity', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'size', description: 'World size of the object (units)', type: 'number', min: 0.2, max: 4, step: 0.01 },
  { name: 'color', description: 'Sunlight colour', type: 'color' },
  { name: 'particleCount', description: 'Dust motes (CPU simulated)', type: 'number', min: 1000, max: 20000, step: 500 },
  { name: 'temperature', description: 'Air temperature: strength of the Brownian jitter', type: 'number', min: 0, max: 4, step: 0.01 },
  { name: 'turbulence', description: 'Strength of the slow turbulent air currents', type: 'number', min: 0, max: 4, step: 0.01 },
  { name: 'beamAngle', description: 'Sun elevation in degrees', type: 'number', min: 10, max: 80, step: 0.5 },
  { name: 'beamWidth', description: 'Width of the window', type: 'number', min: 0.1, max: 0.7, step: 0.01 },
  { name: 'windowPanes', description: 'Window columns: mullions cast shadow lines through the beam', type: 'number', min: 1, max: 5, step: 1 },
  { name: 'anisotropy', description: 'Forward-scattering strength g of the dust (Henyey–Greenstein)', type: 'number', min: 0, max: 0.95, step: 0.01 },
  { name: 'hazeDensity', description: 'Density of the fine haze that makes the light shaft visible', type: 'number', min: 0, max: 2, step: 0.01 },
  { name: 'aperture', description: 'Lens aperture: out-of-focus motes become bokeh discs (0 = pinhole)', type: 'number', min: 0, max: 2, step: 0.01 },
  { name: 'ambientColor', description: 'Skylight tint of motes outside the beam', type: 'color' },
  { name: 'pointerMode', description: 'What the cursor is: off, a hand in the air, a torch, or a charged rod', type: 'select', options: ['none', 'hand', 'torch', 'charge'], optionLabels: ['Off', 'Hand', 'Torch', 'Charged rod'] },
  { name: 'pointerStrength', description: 'Strength of the air push / light / charge (0 = no interaction)', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'pointerRadius', description: 'Size of the hand, reach of the light, or reach of the charge', type: 'number', min: 0.2, max: 3, step: 0.01 },
  { name: 'pointerColor', description: 'Torch light colour / corona glow colour', type: 'color' },
  { name: 'trailMode', description: 'Shutter drag, swirl threads or afterglow', type: 'select', options: ['none', 'streak', 'comet', 'echo'], optionLabels: ['Off', 'Shutter drag', 'Swirl threads', 'Afterglow'] },
  { name: 'trailLength', description: 'Trail duration in seconds', type: 'number', min: 0.2, max: 6, step: 0.05 },
  { name: 'trailOpacity', description: 'Trail brightness', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'trailColor', description: 'Colour trails cool toward', type: 'color' },
  { name: 'trailShare', description: 'Fraction of motes that leave trails', type: 'number', min: 0.02, max: 1, step: 0.01 },
];

export const bioluminescentWakeParticlesProperties: OptionalProperty[] = [
  { name: 'intensity', description: 'Overall brightness', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'speed', description: 'Simulation time scale', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'opacity', description: 'Overall opacity', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'size', description: 'World size of the object (units)', type: 'number', min: 0.2, max: 4, step: 0.01 },
  { name: 'color', description: 'Luminescence colour (luciferin blue)', type: 'color' },
  { name: 'particleCount', description: 'Plankton cells (CPU simulated)', type: 'number', min: 4000, max: 60000, step: 1000 },
  { name: 'swellHeight', description: 'Swell amplitude: bigger waves shear the surface and light the crests', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'current', description: 'Drift speed of the water', type: 'number', min: 0, max: 2, step: 0.01 },
  { name: 'sensitivity', description: 'How easily cells flash (lower thresholds)', type: 'number', min: 0.2, max: 4, step: 0.01 },
  { name: 'recovery', description: 'Seconds a cell needs to recharge after flashing', type: 'number', min: 0.5, max: 30, step: 0.1 },
  { name: 'glowTime', description: 'Flash duration', type: 'number', min: 0.3, max: 4, step: 0.01 },
  { name: 'waterClarity', description: 'How far light travels in the water before it is absorbed', type: 'number', min: 0.2, max: 3, step: 0.01 },
  { name: 'deepColor', description: 'Colour light shifts toward when it comes from deeper water', type: 'color' },
  { name: 'moonlight', description: 'Moon glitter on the surface (0 = none)', type: 'number', min: 0, max: 2, step: 0.01 },
  { name: 'seed', description: 'Layout seed: a different arrangement with the same character', type: 'number', min: 1, max: 999, step: 1 },
  { name: 'quality', description: 'Detail level: scales particle counts and trail caps', type: 'select', options: ['low', 'medium', 'high'], optionLabels: ['Low', 'Medium', 'High'] },
  { name: 'pointerMode', description: 'What the cursor is: off, a hand in the water, falling pebbles, or a fish that hunts it', type: 'select', options: ['none', 'hand', 'pebble', 'fish'], optionLabels: ['Off', 'Hand', 'Pebbles', 'Hunting fish'] },
  { name: 'pointerStrength', description: 'Stroke force / pebble size / fish speed (0 = no interaction)', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'pointerRadius', description: 'Size of the hand, the pebbles or the fish', type: 'number', min: 0.2, max: 3, step: 0.01 },
  { name: 'pointerColor', description: 'Splash colour', type: 'color' },
  { name: 'trailMode', description: 'Long exposure, glow threads or afterglow', type: 'select', options: ['none', 'streak', 'comet', 'echo'], optionLabels: ['Off', 'Long exposure', 'Glow threads', 'Afterglow'] },
  { name: 'trailLength', description: 'Trail duration in seconds', type: 'number', min: 0.2, max: 6, step: 0.05 },
  { name: 'trailOpacity', description: 'Trail brightness', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'trailColor', description: 'Colour trails cool toward', type: 'color' },
  { name: 'trailShare', description: 'Fraction of cells that can leave trails', type: 'number', min: 0.02, max: 1, step: 0.01 },
];

export const electronOrbitalsParticlesProperties: OptionalProperty[] = [
  { name: 'intensity', description: 'Overall brightness', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'speed', description: 'Simulation time scale', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'opacity', description: 'Overall opacity', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'size', description: 'World size of the object (units)', type: 'number', min: 0.2, max: 4, step: 0.01 },
  { name: 'color', description: 'Colour at phase 0', type: 'color' },
  { name: 'particleCount', description: 'Bohmian particles (CPU simulated)', type: 'number', min: 2000, max: 60000, step: 1000 },
  { name: 'stateA', description: 'First orbital (n, l, m)', type: 'select', options: ['1s', '2s', '2p0', '2p+1', '3s', '3p0', '3p+1', '3d0', '3d+1', '3d+2', '4s', '4p+1', '4d+1', '4d+2', '4f0', '4f+1', '4f+2', '4f+3'], optionLabels: ['1s (m = )', '2s (m = )', '2p (m = 0)', '2p (m = +1)', '3s (m = )', '3p (m = 0)', '3p (m = +1)', '3d (m = 0)', '3d (m = +1)', '3d (m = +2)', '4s (m = )', '4p (m = +1)', '4d (m = +1)', '4d (m = +2)', '4f (m = 0)', '4f (m = +1)', '4f (m = +2)', '4f (m = +3)'] },
  { name: 'stateB', description: 'Second orbital (n, l, m)', type: 'select', options: ['1s', '2s', '2p0', '2p+1', '3s', '3p0', '3p+1', '3d0', '3d+1', '3d+2', '4s', '4p+1', '4d+1', '4d+2', '4f0', '4f+1', '4f+2', '4f+3'], optionLabels: ['1s (m = )', '2s (m = )', '2p (m = 0)', '2p (m = +1)', '3s (m = )', '3p (m = 0)', '3p (m = +1)', '3d (m = 0)', '3d (m = +1)', '3d (m = +2)', '4s (m = )', '4p (m = +1)', '4d (m = +1)', '4d (m = +2)', '4f (m = 0)', '4f (m = +1)', '4f (m = +2)', '4f (m = +3)'] },
  { name: 'mix', description: 'Share of the second orbital in the superposition', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'timeScale', description: 'Atomic time per second: speed of the breathing and circulation', type: 'number', min: 0, max: 4, step: 0.01 },
  { name: 'phaseColor', description: 'Colour at phase pi (the cycle runs through both colours)', type: 'color' },
  { name: 'cloudDensity', description: 'Brightness of the |psi|^2 probability haze', type: 'number', min: 0, max: 2, step: 0.01 },
  { name: 'phaseFronts', description: 'Glow of the wavefronts (surfaces of constant phase) inside the cloud', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'pointSize', description: 'Particle size', type: 'number', min: 0.3, max: 3, step: 0.01 },
  { name: 'seed', description: 'Layout seed: a different arrangement with the same character', type: 'number', min: 1, max: 999, step: 1 },
  { name: 'quality', description: 'Detail level: scales particle counts and trail caps', type: 'select', options: ['low', 'medium', 'high'], optionLabels: ['Low', 'Medium', 'High'] },
  { name: 'pointerMode', description: 'What the cursor is: off, a resonant photon source, a magnet, or a position detector', type: 'select', options: ['none', 'photon', 'magnet', 'measure'], optionLabels: ['Off', 'Photon', 'Magnet', 'Detector'] },
  { name: 'pointerStrength', description: 'Drive strength / field strength / detector efficiency (0 = no interaction)', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'pointerRadius', description: 'Reach of the light, or the detector window size', type: 'number', min: 0.2, max: 3, step: 0.01 },
  { name: 'pointerColor', description: 'Colour of emitted photons and detector clicks', type: 'color' },
  { name: 'trailMode', description: 'Long exposure, Bohm trajectories or afterglow', type: 'select', options: ['none', 'streak', 'comet', 'echo'], optionLabels: ['Off', 'Long exposure', 'Bohm trajectories', 'Afterglow'] },
  { name: 'trailLength', description: 'Trail duration in seconds', type: 'number', min: 0.2, max: 6, step: 0.05 },
  { name: 'trailOpacity', description: 'Trail brightness', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'trailColor', description: 'Colour trails cool toward', type: 'color' },
  { name: 'trailShare', description: 'Fraction of particles that leave trails', type: 'number', min: 0.02, max: 1, step: 0.01 },
];

export const grinderSparksParticlesProperties: OptionalProperty[] = [
  { name: 'intensity', description: 'Overall brightness', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'speed', description: 'Simulation time scale', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'opacity', description: 'Overall opacity', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'size', description: 'World size of the object (units)', type: 'number', min: 0.2, max: 4, step: 0.01 },
  { name: 'color', description: 'Tint of the hottest sparks', type: 'color' },
  { name: 'particleCount', description: 'Spark pool size (CPU simulated)', type: 'number', min: 1000, max: 20000, step: 500 },
  { name: 'sparkRate', description: 'Sparks per second', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'wheelSpeed', description: 'Rim speed in m/s: launch speed of the sparks', type: 'number', min: 10, max: 80, step: 0.5 },
  { name: 'sprayAngle', description: 'Fan spread in degrees', type: 'number', min: 2, max: 40, step: 0.5 },
  { name: 'carbon', description: 'Carbon content: how often sparks burst into stars (spark test)', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'temperature', description: 'Launch temperature in kelvin', type: 'number', min: 1400, max: 2600, step: 10 },
  { name: 'exposure', description: 'Camera exposure: how long cooling sparks stay visible', type: 'number', min: 0.3, max: 3, step: 0.01 },
  { name: 'floorReflect', description: 'Floor reflection strength (0 = matte)', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'emberColor', description: 'Tint of the coolest, dull-red sparks', type: 'color' },
  { name: 'seed', description: 'Layout seed: a different arrangement with the same character', type: 'number', min: 1, max: 999, step: 1 },
  { name: 'quality', description: 'Detail level: scales particle counts and trail caps', type: 'select', options: ['low', 'medium', 'high'], optionLabels: ['Low', 'Medium', 'High'] },
  { name: 'pointerMode', description: 'What the cursor does: off, moves the grinder, aims the spray, or sweeps the air through the sparks', type: 'select', options: ['none', 'wheel', 'aim', 'sweep'], optionLabels: ['Off', 'Move the grinder', 'Aim the spray', 'Air sweep'] },
  { name: 'pointerStrength', description: 'Grinding pressure / aim pressure / strength of the air sweep (0 = no interaction)', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'pointerRadius', description: 'Size of the air sweep', type: 'number', min: 0.2, max: 3, step: 0.01 },
  { name: 'pointerColor', description: 'Tint of the oxygen flare in the air sweep', type: 'color' },
  { name: 'trailMode', description: 'Long exposure, tracer arcs or smoulder', type: 'select', options: ['none', 'streak', 'comet', 'echo'], optionLabels: ['Off', 'Long exposure', 'Tracer arcs', 'Smoulder'] },
  { name: 'trailLength', description: 'Shutter: length of the streaks', type: 'number', min: 0.2, max: 6, step: 0.05 },
  { name: 'trailOpacity', description: 'Trail brightness', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'trailColor', description: 'Colour trails cool toward', type: 'color' },
  { name: 'trailShare', description: 'Fraction of sparks that leave trails', type: 'number', min: 0.02, max: 1, step: 0.01 },
];

export const chladniSandParticlesProperties: OptionalProperty[] = [
  { name: 'intensity', description: 'Overall brightness', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'speed', description: 'Simulation time scale', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'opacity', description: 'Overall opacity', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'size', description: 'World size of the object (units)', type: 'number', min: 0.2, max: 4, step: 0.01 },
  { name: 'color', description: 'Sand colour', type: 'color' },
  { name: 'particleCount', description: 'Sand grains (CPU simulated)', type: 'number', min: 4000, max: 60000, step: 1000 },
  { name: 'frequency', description: 'Drive frequency (mode number): each value rings a different figure', type: 'number', min: 1.5, max: 10, step: 0.01 },
  { name: 'sweep', description: 'Slow glide of the drive frequency through neighbouring resonances (octaves; 0 = hold)', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'damping', description: 'Resonance width: low = sharp, pure figures; high = blended figures', type: 'number', min: 0.01, max: 0.3, step: 0.001 },
  { name: 'amplitude', description: 'Drive strength: thinner or thicker nodal lines, livelier hops', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'hopColor', description: 'Colour of grains in flight, catching the light', type: 'color' },
  { name: 'lightAngle', description: 'Elevation of the raking light in degrees: low = strong relief', type: 'number', min: 5, max: 70, step: 0.5 },
  { name: 'grainSize', description: 'Grain sprite size', type: 'number', min: 0.3, max: 3, step: 0.01 },
  { name: 'seed', description: 'Layout seed: a different arrangement with the same character', type: 'number', min: 1, max: 999, step: 1 },
  { name: 'quality', description: 'Detail level: scales particle counts and trail caps', type: 'select', options: ['low', 'medium', 'high'], optionLabels: ['Low', 'Medium', 'High'] },
  { name: 'pointerMode', description: 'What the cursor does: off, bows the plate edge, touches it with a finger, or taps it', type: 'select', options: ['none', 'bow', 'finger', 'tap'], optionLabels: ['Off', 'Violin bow', 'Finger', 'Tap'] },
  { name: 'pointerStrength', description: 'Bow pressure / finger pressure / tap force (0 = no interaction)', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'pointerRadius', description: 'Bow width / fingertip size / tap size', type: 'number', min: 0.2, max: 3, step: 0.01 },
  { name: 'pointerColor', description: 'Rosin dust colour', type: 'color' },
  { name: 'trailMode', description: 'Long exposure, migration paths or dust haze', type: 'select', options: ['none', 'streak', 'comet', 'echo'], optionLabels: ['Off', 'Long exposure', 'Migration paths', 'Dust haze'] },
  { name: 'trailLength', description: 'Trail duration in seconds', type: 'number', min: 0.2, max: 6, step: 0.05 },
  { name: 'trailOpacity', description: 'Trail brightness', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'trailColor', description: 'Colour trails cool toward', type: 'color' },
  { name: 'trailShare', description: 'Fraction of grains that leave trails', type: 'number', min: 0.02, max: 1, step: 0.01 },
];

export const faradayPowderParticlesProperties: OptionalProperty[] = [
  { name: 'intensity', description: 'Overall brightness', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'speed', description: 'Simulation time scale', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'opacity', description: 'Overall opacity', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'size', description: 'World size of the object (units)', type: 'number', min: 0.2, max: 4, step: 0.01 },
  { name: 'color', description: 'Powder colour at rest (the ember)', type: 'color' },
  { name: 'particleCount', description: 'Powder particles (CPU simulated)', type: 'number', min: 2000, max: 40000, step: 500 },
  { name: 'frequency', description: 'Drive frequency (mode number): each value rings a different figure', type: 'number', min: 1.5, max: 10, step: 0.01 },
  { name: 'sweep', description: 'Slow glide of the drive frequency through neighbouring resonances (octaves; 0 = hold)', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'damping', description: 'Resonance width: low = sharp, pure figures; high = blended figures', type: 'number', min: 0.01, max: 0.3, step: 0.001 },
  { name: 'amplitude', description: 'Drive strength: how hard the plate shakes the powder', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'glowColor', description: 'Colour of powder churning in the strongest antinodes', type: 'color' },
  { name: 'hover', description: 'How high the heaps float above the plate', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'swirl', description: 'Spin of the heaps (acoustic streaming cells)', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'puffSize', description: 'Powder puff size', type: 'number', min: 0.3, max: 3, step: 0.01 },
  { name: 'seed', description: 'Layout seed: a different arrangement with the same character', type: 'number', min: 1, max: 999, step: 1 },
  { name: 'quality', description: 'Detail level: scales particle counts and trail caps', type: 'select', options: ['low', 'medium', 'high'], optionLabels: ['Low', 'Medium', 'High'] },
  { name: 'pointerMode', description: 'What the cursor does: off, bows the plate edge, touches it with a finger, or taps it', type: 'select', options: ['none', 'bow', 'finger', 'tap'], optionLabels: ['Off', 'Violin bow', 'Finger', 'Tap'] },
  { name: 'pointerStrength', description: 'Bow pressure / finger pressure / tap force (0 = no interaction)', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'pointerRadius', description: 'Bow width / fingertip size / tap size', type: 'number', min: 0.2, max: 3, step: 0.01 },
  { name: 'pointerColor', description: 'Rosin dust colour', type: 'color' },
  { name: 'trailMode', description: 'Long exposure, swirl threads or smoke haze', type: 'select', options: ['none', 'streak', 'comet', 'echo'], optionLabels: ['Off', 'Long exposure', 'Swirl threads', 'Smoke haze'] },
  { name: 'trailLength', description: 'Trail duration in seconds', type: 'number', min: 0.2, max: 6, step: 0.05 },
  { name: 'trailOpacity', description: 'Trail brightness', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'trailColor', description: 'Colour trails cool toward', type: 'color' },
  { name: 'trailShare', description: 'Fraction of powder that leaves trails', type: 'number', min: 0.02, max: 1, step: 0.01 },
];

export const neonRainParticlesProperties: OptionalProperty[] = [
  { name: 'intensity', description: 'Overall brightness', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'speed', description: 'Simulation time scale', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'opacity', description: 'Overall opacity', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'size', description: 'World size of the object (units)', type: 'number', min: 0.2, max: 4, step: 0.01 },
  { name: 'color', description: 'First neon light colour', type: 'color' },
  { name: 'particleCount', description: 'Raindrop pool (CPU simulated; splash droplets come on top)', type: 'number', min: 1000, max: 20000, step: 500 },
  { name: 'rainRate', description: 'Rain rate in mm/h: more drops, and bigger ones', type: 'number', min: 1, max: 80, step: 0.5 },
  { name: 'windSpeed', description: 'Breeze across the street in m/s (negative = from the other side)', type: 'number', min: -6, max: 6, step: 0.05 },
  { name: 'gustiness', description: 'Strength of the gust fronts that sweep sheets of rain through', type: 'number', min: 0, max: 2, step: 0.01 },
  { name: 'neonColor2', description: 'Second neon light colour', type: 'color' },
  { name: 'lampColor', description: 'Sodium streetlamp light from above', type: 'color' },
  { name: 'neonLight', description: 'Strength of the neon light falling on the rain (the lights themselves stay off-screen)', type: 'number', min: 0, max: 2, step: 0.01 },
  { name: 'aperture', description: 'Lens aperture: out-of-focus drops become bokeh discs (0 = pinhole)', type: 'number', min: 0, max: 2, step: 0.01 },
  { name: 'dropSize', description: 'Drop sprite size', type: 'number', min: 0.3, max: 3, step: 0.01 },
  { name: 'seed', description: 'Layout seed: a different arrangement with the same character', type: 'number', min: 1, max: 999, step: 1 },
  { name: 'quality', description: 'Detail level: scales particle counts and trail caps', type: 'select', options: ['low', 'medium', 'high'], optionLabels: ['Low', 'Medium', 'High'] },
  { name: 'pointerMode', description: 'What the cursor is: off, an umbrella, a gust of wind, or an oncoming headlight', type: 'select', options: ['none', 'umbrella', 'gust', 'headlight'], optionLabels: ['Off', 'Umbrella', 'Gust', 'Headlight'] },
  { name: 'pointerStrength', description: 'Umbrella size / gust force / headlight power (0 = no interaction)', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'pointerRadius', description: 'Umbrella radius / gust size / beam width', type: 'number', min: 0.2, max: 3, step: 0.01 },
  { name: 'pointerColor', description: 'Headlight colour, and the tint of canopy splashes', type: 'color' },
  { name: 'trailMode', description: 'Shutter streaks, wet threads or splash afterglow', type: 'select', options: ['none', 'streak', 'comet', 'echo'], optionLabels: ['Off', 'Shutter streaks', 'Wet threads', 'Splash afterglow'] },
  { name: 'trailLength', description: 'Shutter: length of the streaks', type: 'number', min: 0.2, max: 6, step: 0.05 },
  { name: 'trailOpacity', description: 'Trail brightness', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'trailColor', description: 'Colour trails cool toward', type: 'color' },
  { name: 'trailShare', description: 'Fraction of drops that leave trails', type: 'number', min: 0.02, max: 1, step: 0.01 },
];

export const magneticBottleParticlesProperties: OptionalProperty[] = [
  { name: 'intensity', description: 'Overall brightness', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'speed', description: 'Simulation time scale', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'opacity', description: 'Overall opacity', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'size', description: 'World size of the object (units)', type: 'number', min: 0.2, max: 4, step: 0.01 },
  { name: 'color', description: 'Colour of the positive family', type: 'color' },
  { name: 'particleCount', description: 'Particles on the surface (each draws one woven line)', type: 'number', min: 4, max: 200, step: 1 },
  { name: 'windings', description: 'Field strength: turns per unit climb (denser weave)', type: 'number', min: 0.2, max: 5, step: 0.01 },
  { name: 'pitchSpread', description: 'Spread of pitch angles: how far up the shape the orbits reach before they mirror', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'lineLife', description: 'Seconds a drawn line lingers', type: 'number', min: 0.5, max: 20, step: 0.1 },
  { name: 'lineDensity', description: 'Points per unit of line', type: 'number', min: 0.3, max: 3, step: 0.01 },
  { name: 'counterColor', description: 'Colour of the negative (counter-rotating) family', type: 'color' },
  { name: 'glow', description: 'Brightness of the mirror rings and heads', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'seed', description: 'Layout seed: a different arrangement with the same character', type: 'number', min: 1, max: 999, step: 1 },
  { name: 'quality', description: 'Detail level: scales particle counts and trail caps', type: 'select', options: ['low', 'medium', 'high'], optionLabels: ['Low', 'Medium', 'High'] },
  { name: 'pointerMode', description: 'What the cursor is: off, a magnet (pinch), an electric field (drift) or an RF antenna (heat)', type: 'select', options: ['none', 'pinch', 'drift', 'heat'], optionLabels: ['Off', 'Pinch', 'Drift', 'Heat'] },
  { name: 'pointerStrength', description: 'Field / drift / heating strength (0 = no interaction)', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'pointerRadius', description: 'Reach of the cursor', type: 'number', min: 0.2, max: 3, step: 0.01 },
  { name: 'pointerColor', description: 'Colour of heated particles', type: 'color' },
  { name: 'trailMode', description: 'Motion blur, gyro tails or afterglow', type: 'select', options: ['none', 'streak', 'comet', 'echo'], optionLabels: ['Off', 'Motion blur', 'Gyro tails', 'Afterglow'] },
  { name: 'trailLength', description: 'Trail duration in seconds', type: 'number', min: 0.2, max: 6, step: 0.05 },
  { name: 'trailOpacity', description: 'Trail brightness', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'trailColor', description: 'Colour the tails fade into, from the family colour at the head', type: 'color' },
  { name: 'trailShare', description: 'Fraction of particles that leave trails', type: 'number', min: 0.02, max: 1, step: 0.01 },
];

export const shapeBurstParticlesProperties: OptionalProperty[] = [
  { name: 'intensity', description: 'Overall brightness', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'speed', description: 'Simulation time scale', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'opacity', description: 'Overall opacity', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'size', description: 'World size of the object (units)', type: 'number', min: 0.2, max: 4, step: 0.01 },
  { name: 'color', description: 'Colour of the positive family once it has landed', type: 'color' },
  { name: 'particleCount', description: 'Particles per burst', type: 'number', min: 60, max: 3000, step: 10 },
  { name: 'interval', description: 'Seconds between bursts', type: 'number', min: 0.6, max: 8, step: 0.05 },
  { name: 'formSpeed', description: 'Drag rate: how fast the burst settles into the shape', type: 'number', min: 0.5, max: 8, step: 0.01 },
  { name: 'fieldStrength', description: 'Magnetic field: how far the paths curl on the way out', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'holdTime', description: 'Seconds the shape holds before it dissolves', type: 'number', min: 0, max: 6, step: 0.05 },
  { name: 'dissolve', description: 'Outward drift while the shape fades', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'counterColor', description: 'Colour of the negative family once it has landed', type: 'color' },
  { name: 'heatColor', description: 'White-hot colour at launch', type: 'color' },
  { name: 'headSize', description: 'Particle size', type: 'number', min: 0.2, max: 3, step: 0.01 },
  { name: 'seed', description: 'Layout seed: a different arrangement with the same character', type: 'number', min: 1, max: 999, step: 1 },
  { name: 'quality', description: 'Detail level: scales particle counts and trail caps', type: 'select', options: ['low', 'medium', 'high'], optionLabels: ['Low', 'Medium', 'High'] },
  { name: 'pointerMode', description: 'What the cursor does: off, detonates bursts, curls them (magnet) or pulls them (gravity)', type: 'select', options: ['none', 'detonate', 'magnet', 'gravity'], optionLabels: ['Off', 'Detonate', 'Magnet', 'Gravity'] },
  { name: 'pointerStrength', description: 'Burst size / field / pull (0 = no interaction)', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'pointerRadius', description: 'Size of cursor bursts / reach of the field or pull', type: 'number', min: 0.2, max: 3, step: 0.01 },
  { name: 'pointerColor', description: 'Glow of particles the cursor is acting on', type: 'color' },
  { name: 'trailMode', description: 'Motion blur, spiral tails or embers', type: 'select', options: ['none', 'streak', 'comet', 'echo'], optionLabels: ['Off', 'Motion blur', 'Spiral tails', 'Embers'] },
  { name: 'trailLength', description: 'Tail duration in seconds', type: 'number', min: 0.2, max: 6, step: 0.05 },
  { name: 'trailOpacity', description: 'Tail brightness', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'trailColor', description: 'Colour the tails fade into', type: 'color' },
  { name: 'trailShare', description: 'Fraction of particles that leave tails', type: 'number', min: 0.02, max: 1, step: 0.01 },
];

export const shapeFlowParticlesProperties: OptionalProperty[] = [
  { name: 'intensity', description: 'Overall brightness', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'speed', description: 'Simulation time scale', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'opacity', description: 'Overall opacity', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'size', description: 'World size of the object (units)', type: 'number', min: 0.2, max: 4, step: 0.01 },
  { name: 'color', description: 'Colour of high pressure (the nose, the slow wake)', type: 'color' },
  { name: 'particleCount', description: 'Tracer particles', type: 'number', min: 300, max: 8000, step: 50 },
  { name: 'flowSpeed', description: 'Wind speed', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'windPitch', description: 'Angle of the wind to the horizontal (degrees): the shape meets it tilted', type: 'number', min: -60, max: 60, step: 1 },
  { name: 'rake', description: 'Where the streams are released: a ring round the body, one vertical sheet, or a cross', type: 'select', options: ['tube', 'sheet', 'cross'], optionLabels: ['Stream tube', 'Smoke sheet', 'Cross'] },
  { name: 'lanes', description: 'Number of stream lanes in the rake', type: 'number', min: 6, max: 128, step: 1 },
  { name: 'streamWidth', description: 'Size of the rake compared with the tunnel', type: 'number', min: 0.2, max: 1, step: 0.01 },
  { name: 'turbulence', description: 'Strength of the wake eddies behind the shape', type: 'number', min: 0, max: 2, step: 0.01 },
  { name: 'fastColor', description: 'Colour of low pressure (fast flow round the sides)', type: 'color' },
  { name: 'headSize', description: 'Tracer size', type: 'number', min: 0.2, max: 3, step: 0.01 },
  { name: 'seed', description: 'Layout seed: a different arrangement with the same character', type: 'number', min: 1, max: 999, step: 1 },
  { name: 'quality', description: 'Detail level: scales particle counts and trail caps', type: 'select', options: ['low', 'medium', 'high'], optionLabels: ['Low', 'Medium', 'High'] },
  { name: 'pointerMode', description: 'What the cursor is: off, a second obstacle, a jet or a vortex', type: 'select', options: ['none', 'obstacle', 'jet', 'vortex'], optionLabels: ['Off', 'Second obstacle', 'Jet', 'Vortex'] },
  { name: 'pointerStrength', description: 'Obstacle size / jet force / vortex circulation (0 = no interaction)', type: 'number', min: 0, max: 3, step: 0.01 },
  { name: 'pointerRadius', description: 'Reach of the cursor', type: 'number', min: 0.2, max: 3, step: 0.01 },
  { name: 'pointerColor', description: 'Glow of tracers the cursor is acting on', type: 'color' },
  { name: 'trailMode', description: 'Motion blur, streaklines or smoke', type: 'select', options: ['none', 'streak', 'comet', 'echo'], optionLabels: ['Off', 'Motion blur', 'Streaklines', 'Smoke'] },
  { name: 'trailLength', description: 'Streakline length in seconds', type: 'number', min: 0.2, max: 6, step: 0.05 },
  { name: 'trailOpacity', description: 'Streakline brightness', type: 'number', min: 0, max: 1, step: 0.01 },
  { name: 'trailColor', description: 'Colour the streaklines fade into', type: 'color' },
  { name: 'trailShare', description: 'Fraction of tracers that leave streaklines', type: 'number', min: 0.02, max: 1, step: 0.01 },
];

// Shape tab: the parameters of each shape type (config.shape; see PARTICLE_SHAPE_DEFAULTS in core).
// Box size is edited as three sliders (sizeX / sizeY / sizeZ) over config.shape.size.
export const PARTICLE_SHAPE_TYPE_LABELS: Record<string, string> = {
  cone: 'Cone', cylinder: 'Cylinder', sphere: 'Sphere', capsule: 'Capsule', torus: 'Torus', box: 'Box',
  tetrahedron: 'Tetrahedron', octahedron: 'Octahedron', icosahedron: 'Icosahedron', dodecahedron: 'Dodecahedron',
};
export const PARTICLE_SHAPE_PARAMS: Record<string, OptionalProperty> = {
  radius: { name: 'radius', label: 'Radius', description: 'Radius of the shape', type: 'number', min: 0.05, max: 2, step: 0.01 },
  radiusTop: { name: 'radiusTop', label: 'Radius Top', description: 'Radius at the top (0 = a point)', type: 'number', min: 0, max: 2, step: 0.01 },
  radiusBottom: { name: 'radiusBottom', label: 'Radius Bottom', description: 'Radius at the bottom (0 = a point)', type: 'number', min: 0, max: 2, step: 0.01 },
  height: { name: 'height', label: 'Height', description: 'Height of the shape', type: 'number', min: 0.05, max: 3, step: 0.01 },
  length: { name: 'length', label: 'Length', description: 'Length of the straight middle section', type: 'number', min: 0, max: 3, step: 0.01 },
  tube: { name: 'tube', label: 'Tube', description: 'Thickness of the ring', type: 'number', min: 0.02, max: 1, step: 0.01 },
  sizeX: { name: 'sizeX', label: 'Width', description: 'Box width', type: 'number', min: 0.05, max: 3, step: 0.01 },
  sizeY: { name: 'sizeY', label: 'Height', description: 'Box height', type: 'number', min: 0.05, max: 3, step: 0.01 },
  sizeZ: { name: 'sizeZ', label: 'Depth', description: 'Box depth', type: 'number', min: 0.05, max: 3, step: 0.01 },
  radialSegments: { name: 'radialSegments', label: 'Radial Segments', description: 'Facets round the axis (few = a pyramid or prism)', type: 'number', min: 3, max: 128, step: 1 },
  tubularSegments: { name: 'tubularSegments', label: 'Tubular Segments', description: 'Facets along the ring', type: 'number', min: 3, max: 200, step: 1 },
  capSegments: { name: 'capSegments', label: 'Cap Segments', description: 'Facets in the rounded caps', type: 'number', min: 1, max: 16, step: 1 },
  segments: { name: 'segments', label: 'Segments', description: 'Facets round the sphere', type: 'number', min: 3, max: 64, step: 1 },
  rings: { name: 'rings', label: 'Rings', description: 'Facets from pole to pole', type: 'number', min: 2, max: 64, step: 1 },
  detail: { name: 'detail', label: 'Detail', description: 'Subdivision level (0 = flat faces)', type: 'number', min: 0, max: 5, step: 1 },
};

export const PARTICLES_PROPERTIES: Record<GenerativeParticlesType, OptionalProperty[]> = {
  tidalStream: tidalStreamParticlesProperties,
  brownianDust: brownianDustParticlesProperties,
  bioluminescentWake: bioluminescentWakeParticlesProperties,
  electronOrbitals: electronOrbitalsParticlesProperties,
  grinderSparks: grinderSparksParticlesProperties,
  chladniSand: chladniSandParticlesProperties,
  faradayPowder: faradayPowderParticlesProperties,
  neonRain: neonRainParticlesProperties,
  magneticBottle: magneticBottleParticlesProperties,
  shapeBurst: shapeBurstParticlesProperties,
  shapeFlow: shapeFlowParticlesProperties,
};
