// Property table for the text looks (type 'text', config.type set). The registry (../registry.ts) is built on these tables.
import type { OptionalProperty } from './optionalProperties';
import type { TextObjectType } from '../../types/textObjects';

// =============================================================================
// TEXT OBJECTS OPTIONAL PROPERTIES
// Order: the look's own knobs, then the shared ones: text, font, draw, erase, playback.
// =============================================================================

export const TEXT_PROPERTIES: Record<TextObjectType, OptionalProperty[]> = {
    handwriting: [
        { name: 'weight', label: 'Pen weight', description: 'Thickness of the pen line', type: 'number', min: 0.4, max: 2.5, step: 0.01 },
        { name: 'color', label: 'Ink', description: 'Colour of the dry ink', type: 'color' },
        { name: 'color2', label: 'Wet ink', description: 'Colour of the ink while it is still wet', type: 'color' },
        { name: 'wetTime', label: 'Drying time', description: 'How long the ink takes to dry', type: 'number', min: 0.2, max: 3, step: 0.05, unit: 's' },
        { name: 'sheen', label: 'Sheen', description: 'A faint glint that drifts over the dry ink', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'penGlow', label: 'Pen glow', description: 'Glow at the pen tip while writing', type: 'number', min: 0, max: 2, step: 0.05 },
        { name: 'opacity', label: 'Opacity', description: 'Overall opacity', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'text', label: 'Text', description: 'The words; a new line starts a second line', type: 'string' },
        { name: 'font', label: 'Font', description: 'Typeface of the text (every look uses the same fonts)', type: 'select', options: ['inter', 'roboto', 'montserrat', 'poppins', 'oswald', 'bebas-neue', 'playfair-display', 'lora', 'caveat', 'kalam', 'handlee', 'patrick-hand', 'architects-daughter', 'indie-flower', 'gochi-hand', 'nanum-pen-script', 'mynerve', 'dancing-script', 'courgette', 'satisfy', 'kaushan-script', 'sriracha', 'pacifico'], optionLabels: ['Inter', 'Roboto', 'Montserrat', 'Poppins', 'Oswald', 'Bebas Neue', 'Playfair Display', 'Lora', 'Caveat', 'Kalam', 'Handlee', 'Patrick Hand', 'Architect\'s Daughter', 'Indie Flower', 'Gochi Hand', 'Nanum Pen', 'Mynerve', 'Dancing Script', 'Courgette', 'Satisfy', 'Kaushan Script', 'Sriracha', 'Pacifico'] },
        { name: 'drawMethod', label: 'Draw', description: 'How the text appears when it is shown (rebuilds)', type: 'select', options: ['pen', 'trace', 'bothEnds', 'wipe', 'radial', 'scatter', 'dissolve', 'fade', 'none'], optionLabels: ['Pen', 'Trace', 'Both ends', 'Wipe', 'Radial', 'Scatter', 'Dissolve', 'Fade', 'Off'] },
        { name: 'drawDuration', label: 'Draw duration', description: 'How long the draw animation takes', type: 'number', min: 0.2, max: 15, step: 0.05, unit: 's' },
        { name: 'drawEase', label: 'Draw easing', description: 'Easing of the draw animation', type: 'select', options: ['easeInOut', 'linear', 'easeOut', 'easeIn'], optionLabels: ['Smooth', 'Linear', 'Out', 'In'] },
        { name: 'drawStagger', label: 'Draw stagger', description: 'How much the letters are staggered in time, for Trace and Both ends (rebuilds)', type: 'number', min: 0, max: 0.95, step: 0.01 },
        { name: 'drawAngle', label: 'Draw direction', description: 'Direction of the sweep, for Wipe (rebuilds)', type: 'number', min: -180, max: 180, step: 1, unit: '°' },
        { name: 'eraseMethod', label: 'Erase', description: 'How the text disappears when it is switched off (rebuilds)', type: 'select', options: ['fade', 'undraw', 'wipe', 'radial', 'scatter', 'dissolve', 'trace', 'bothEnds', 'pen', 'cut', 'none'], optionLabels: ['Fade', 'Reverse', 'Wipe', 'Radial', 'Scatter', 'Dissolve', 'Trace', 'Both ends', 'Pen', 'Cut', 'Off'] },
        { name: 'eraseDuration', label: 'Erase duration', description: 'How long the erase animation takes', type: 'number', min: 0.2, max: 15, step: 0.05, unit: 's' },
        { name: 'eraseEase', label: 'Erase easing', description: 'Easing of the erase animation', type: 'select', options: ['easeInOut', 'linear', 'easeOut', 'easeIn'], optionLabels: ['Smooth', 'Linear', 'Out', 'In'] },
        { name: 'eraseStagger', label: 'Erase stagger', description: 'How much the letters are staggered in time, for Trace and Both ends (rebuilds)', type: 'number', min: 0, max: 0.95, step: 0.01 },
        { name: 'eraseAngle', label: 'Erase direction', description: 'Direction of the sweep, for Wipe (rebuilds)', type: 'number', min: -180, max: 180, step: 1, unit: '°' },
        { name: 'autoPlay', label: 'Play on load', description: 'Play the draw animation when the scene starts', type: 'boolean' },
        { name: 'loop', label: 'Loop', description: 'Repeat hidden, draw, hold, erase, hidden', type: 'boolean' },
        { name: 'yoyo', label: 'Yoyo', description: 'Play the whole cycle forward, then backward', type: 'boolean' },
        { name: 'holdTime', label: 'Hold', description: 'How long the finished text stays before it is erased (loop)', type: 'number', min: 0, max: 10, step: 0.1, unit: 's' },
        { name: 'hiddenTime', label: 'Hidden pause', description: 'Pause with nothing shown between cycles (loop)', type: 'number', min: 0, max: 5, step: 0.1, unit: 's' },
    ],
    neonTube: [
        { name: 'color', label: 'Tube colour', description: 'Colour of the glowing gas', type: 'color' },
        { name: 'glow', label: 'Glow', description: 'Strength of the halo', type: 'number', min: 0, max: 2, step: 0.05 },
        { name: 'tube', label: 'Tube thickness', description: 'Thickness of the glass tube', type: 'number', min: 0.015, max: 0.12, step: 0.001 },
        { name: 'flicker', label: 'Flicker', description: 'Stutter on ignition, mains hum and the odd micro-dip', type: 'number', min: 0, max: 1, step: 0.05 },
        { name: 'color2', label: 'Hot core', description: 'Colour of the hot core', type: 'color' },
        { name: 'core', label: 'Core width', description: 'Width of the bright core', type: 'number', min: 0.08, max: 0.5, step: 0.01 },
        { name: 'offLevel', label: 'Unlit glass', description: 'How visible the tube is before it ignites', type: 'number', min: 0, max: 0.4, step: 0.01 },
        { name: 'opacity', label: 'Opacity', description: 'Overall opacity', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'text', label: 'Text', description: 'The words; a new line starts a second line', type: 'string' },
        { name: 'font', label: 'Font', description: 'Typeface of the text (every look uses the same fonts)', type: 'select', options: ['inter', 'roboto', 'montserrat', 'poppins', 'oswald', 'bebas-neue', 'playfair-display', 'lora', 'caveat', 'kalam', 'handlee', 'patrick-hand', 'architects-daughter', 'indie-flower', 'gochi-hand', 'nanum-pen-script', 'mynerve', 'dancing-script', 'courgette', 'satisfy', 'kaushan-script', 'sriracha', 'pacifico'], optionLabels: ['Inter', 'Roboto', 'Montserrat', 'Poppins', 'Oswald', 'Bebas Neue', 'Playfair Display', 'Lora', 'Caveat', 'Kalam', 'Handlee', 'Patrick Hand', 'Architect\'s Daughter', 'Indie Flower', 'Gochi Hand', 'Nanum Pen', 'Mynerve', 'Dancing Script', 'Courgette', 'Satisfy', 'Kaushan Script', 'Sriracha', 'Pacifico'] },
        { name: 'drawMethod', label: 'Draw', description: 'How the text appears when it is shown (rebuilds)', type: 'select', options: ['trace', 'pen', 'bothEnds', 'wipe', 'radial', 'scatter', 'dissolve', 'fade', 'none'], optionLabels: ['Trace', 'Pen', 'Both ends', 'Wipe', 'Radial', 'Scatter', 'Dissolve', 'Fade', 'Off'] },
        { name: 'drawDuration', label: 'Draw duration', description: 'How long the draw animation takes', type: 'number', min: 0.2, max: 15, step: 0.05, unit: 's' },
        { name: 'drawEase', label: 'Draw easing', description: 'Easing of the draw animation', type: 'select', options: ['easeInOut', 'linear', 'easeOut', 'easeIn'], optionLabels: ['Smooth', 'Linear', 'Out', 'In'] },
        { name: 'drawStagger', label: 'Draw stagger', description: 'How much the letters are staggered in time, for Trace and Both ends (rebuilds)', type: 'number', min: 0, max: 0.95, step: 0.01 },
        { name: 'drawAngle', label: 'Draw direction', description: 'Direction of the sweep, for Wipe (rebuilds)', type: 'number', min: -180, max: 180, step: 1, unit: '°' },
        { name: 'eraseMethod', label: 'Erase', description: 'How the text disappears when it is switched off (rebuilds)', type: 'select', options: ['fade', 'undraw', 'wipe', 'radial', 'scatter', 'dissolve', 'trace', 'bothEnds', 'pen', 'cut', 'none'], optionLabels: ['Fade', 'Reverse', 'Wipe', 'Radial', 'Scatter', 'Dissolve', 'Trace', 'Both ends', 'Pen', 'Cut', 'Off'] },
        { name: 'eraseDuration', label: 'Erase duration', description: 'How long the erase animation takes', type: 'number', min: 0.2, max: 15, step: 0.05, unit: 's' },
        { name: 'eraseEase', label: 'Erase easing', description: 'Easing of the erase animation', type: 'select', options: ['easeInOut', 'linear', 'easeOut', 'easeIn'], optionLabels: ['Smooth', 'Linear', 'Out', 'In'] },
        { name: 'eraseStagger', label: 'Erase stagger', description: 'How much the letters are staggered in time, for Trace and Both ends (rebuilds)', type: 'number', min: 0, max: 0.95, step: 0.01 },
        { name: 'eraseAngle', label: 'Erase direction', description: 'Direction of the sweep, for Wipe (rebuilds)', type: 'number', min: -180, max: 180, step: 1, unit: '°' },
        { name: 'autoPlay', label: 'Play on load', description: 'Play the draw animation when the scene starts', type: 'boolean' },
        { name: 'loop', label: 'Loop', description: 'Repeat hidden, draw, hold, erase, hidden', type: 'boolean' },
        { name: 'yoyo', label: 'Yoyo', description: 'Play the whole cycle forward, then backward', type: 'boolean' },
        { name: 'holdTime', label: 'Hold', description: 'How long the finished text stays before it is erased (loop)', type: 'number', min: 0, max: 10, step: 0.1, unit: 's' },
        { name: 'hiddenTime', label: 'Hidden pause', description: 'Pause with nothing shown between cycles (loop)', type: 'number', min: 0, max: 5, step: 0.1, unit: 's' },
    ],
    fourierSketch: [
        { name: 'color', label: 'Line colour', description: 'Colour of the traced letters', type: 'color' },
        { name: 'terms', label: 'Detail', description: 'Number of circles per letter: more is sharper', type: 'number', min: 6, max: 128, step: 1 },
        { name: 'circles', label: 'Circles', description: 'How visible the rotating circles are while drawing', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'glint', label: 'Glints', description: 'Glints that keep circling the finished letters', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'color2', label: 'Hot colour', description: 'Colour of fresh strokes and glints', type: 'color' },
        { name: 'line', label: 'Line width', description: 'Thickness of the traced line', type: 'number', min: 0.01, max: 0.1, step: 0.001 },
        { name: 'trail', label: 'Trail', description: 'How long fresh strokes stay hot', type: 'number', min: 0.1, max: 4, step: 0.05, unit: 's' },
        { name: 'bridges', label: 'Bridges', description: 'Visibility of the lines joining outlines to counters', type: 'number', min: 0, max: 0.6, step: 0.01 },
        { name: 'opacity', label: 'Opacity', description: 'Overall opacity', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'text', label: 'Text', description: 'The words; a new line starts a second line', type: 'string' },
        { name: 'font', label: 'Font', description: 'Typeface of the text (every look uses the same fonts)', type: 'select', options: ['inter', 'roboto', 'montserrat', 'poppins', 'oswald', 'bebas-neue', 'playfair-display', 'lora', 'caveat', 'kalam', 'handlee', 'patrick-hand', 'architects-daughter', 'indie-flower', 'gochi-hand', 'nanum-pen-script', 'mynerve', 'dancing-script', 'courgette', 'satisfy', 'kaushan-script', 'sriracha', 'pacifico'], optionLabels: ['Inter', 'Roboto', 'Montserrat', 'Poppins', 'Oswald', 'Bebas Neue', 'Playfair Display', 'Lora', 'Caveat', 'Kalam', 'Handlee', 'Patrick Hand', 'Architect\'s Daughter', 'Indie Flower', 'Gochi Hand', 'Nanum Pen', 'Mynerve', 'Dancing Script', 'Courgette', 'Satisfy', 'Kaushan Script', 'Sriracha', 'Pacifico'] },
        { name: 'drawMethod', label: 'Draw', description: 'How the text appears when it is shown (rebuilds)', type: 'select', options: ['epicycle', 'trace', 'pen', 'bothEnds', 'wipe', 'radial', 'scatter', 'dissolve', 'fade', 'none'], optionLabels: ['Epicycles', 'Trace', 'Pen', 'Both ends', 'Wipe', 'Radial', 'Scatter', 'Dissolve', 'Fade', 'Off'] },
        { name: 'drawDuration', label: 'Draw duration', description: 'How long the draw animation takes', type: 'number', min: 0.2, max: 15, step: 0.05, unit: 's' },
        { name: 'drawEase', label: 'Draw easing', description: 'Easing of the draw animation', type: 'select', options: ['easeInOut', 'linear', 'easeOut', 'easeIn'], optionLabels: ['Smooth', 'Linear', 'Out', 'In'] },
        { name: 'drawStagger', label: 'Draw stagger', description: 'How much the letters are staggered in time, for Trace and Both ends (rebuilds)', type: 'number', min: 0, max: 0.95, step: 0.01 },
        { name: 'drawAngle', label: 'Draw direction', description: 'Direction of the sweep, for Wipe (rebuilds)', type: 'number', min: -180, max: 180, step: 1, unit: '°' },
        { name: 'eraseMethod', label: 'Erase', description: 'How the text disappears when it is switched off (rebuilds)', type: 'select', options: ['fade', 'undraw', 'wipe', 'radial', 'scatter', 'dissolve', 'trace', 'bothEnds', 'pen', 'cut', 'none'], optionLabels: ['Fade', 'Reverse', 'Wipe', 'Radial', 'Scatter', 'Dissolve', 'Trace', 'Both ends', 'Pen', 'Cut', 'Off'] },
        { name: 'eraseDuration', label: 'Erase duration', description: 'How long the erase animation takes', type: 'number', min: 0.2, max: 15, step: 0.05, unit: 's' },
        { name: 'eraseEase', label: 'Erase easing', description: 'Easing of the erase animation', type: 'select', options: ['easeInOut', 'linear', 'easeOut', 'easeIn'], optionLabels: ['Smooth', 'Linear', 'Out', 'In'] },
        { name: 'eraseStagger', label: 'Erase stagger', description: 'How much the letters are staggered in time, for Trace and Both ends (rebuilds)', type: 'number', min: 0, max: 0.95, step: 0.01 },
        { name: 'eraseAngle', label: 'Erase direction', description: 'Direction of the sweep, for Wipe (rebuilds)', type: 'number', min: -180, max: 180, step: 1, unit: '°' },
        { name: 'autoPlay', label: 'Play on load', description: 'Play the draw animation when the scene starts', type: 'boolean' },
        { name: 'loop', label: 'Loop', description: 'Repeat hidden, draw, hold, erase, hidden', type: 'boolean' },
        { name: 'yoyo', label: 'Yoyo', description: 'Play the whole cycle forward, then backward', type: 'boolean' },
        { name: 'holdTime', label: 'Hold', description: 'How long the finished text stays before it is erased (loop)', type: 'number', min: 0, max: 10, step: 0.1, unit: 's' },
        { name: 'hiddenTime', label: 'Hidden pause', description: 'Pause with nothing shown between cycles (loop)', type: 'number', min: 0, max: 5, step: 0.1, unit: 's' },
    ],
    frostGrowth: [
        { name: 'reach', label: 'Reach', description: 'How far the frost spreads from the letters', type: 'number', min: 0.04, max: 0.5, step: 0.005, unit: 'em' },
        { name: 'branching', label: 'Branching', description: 'Side-branch density of the ice ferns', type: 'number', min: 0.3, max: 1.8, step: 0.05 },
        { name: 'grains', label: 'Grains', description: 'Number of crystal grains; each has its own lattice orientation', type: 'number', min: 1, max: 9, step: 1 },
        { name: 'sparkle', label: 'Sparkle', description: 'Sharp glints travelling over the crystal facets', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'thickness', label: 'Thickness', description: 'Thickness of the ice arms', type: 'number', min: 0.4, max: 2.5, step: 0.05 },
        { name: 'seams', label: 'Grain seams', description: 'Brightness of the boundary lines where grains meet', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'haze', label: 'Frost haze', description: 'Soft frosted glow around the ice', type: 'number', min: 0, max: 1.5, step: 0.01 },
        { name: 'color', label: 'Ice', description: 'Pale colour of thin edges and tips', type: 'color' },
        { name: 'color2', label: 'Deep ice', description: 'Cooler deeper tone of thick spines', type: 'color' },
        { name: 'opacity', label: 'Opacity', description: 'Overall opacity', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'seed', label: 'Seed', description: 'Random seed of the crystal pattern', type: 'number', min: 0, max: 999, step: 1 },
        { name: 'text', label: 'Text', description: 'The words; a new line starts a second line', type: 'string' },
        { name: 'font', label: 'Font', description: 'Typeface of the text (every look uses the same fonts)', type: 'select', options: ['inter', 'roboto', 'montserrat', 'poppins', 'oswald', 'bebas-neue', 'playfair-display', 'lora', 'caveat', 'kalam', 'handlee', 'patrick-hand', 'architects-daughter', 'indie-flower', 'gochi-hand', 'nanum-pen-script', 'mynerve', 'dancing-script', 'courgette', 'satisfy', 'kaushan-script', 'sriracha', 'pacifico'], optionLabels: ['Inter', 'Roboto', 'Montserrat', 'Poppins', 'Oswald', 'Bebas Neue', 'Playfair Display', 'Lora', 'Caveat', 'Kalam', 'Handlee', 'Patrick Hand', 'Architect\'s Daughter', 'Indie Flower', 'Gochi Hand', 'Nanum Pen', 'Mynerve', 'Dancing Script', 'Courgette', 'Satisfy', 'Kaushan Script', 'Sriracha', 'Pacifico'] },
        { name: 'drawMethod', label: 'Draw', description: 'How the text appears when it is shown (rebuilds)', type: 'select', options: ['grow', 'pen', 'trace', 'bothEnds', 'wipe', 'radial', 'scatter', 'dissolve', 'fade', 'none'], optionLabels: ['Grow', 'Pen', 'Trace', 'Both ends', 'Wipe', 'Radial', 'Scatter', 'Dissolve', 'Fade', 'Off'] },
        { name: 'drawDuration', label: 'Draw duration', description: 'How long the draw animation takes', type: 'number', min: 0.2, max: 15, step: 0.05, unit: 's' },
        { name: 'drawEase', label: 'Draw easing', description: 'Easing of the draw animation', type: 'select', options: ['easeInOut', 'linear', 'easeOut', 'easeIn'], optionLabels: ['Smooth', 'Linear', 'Out', 'In'] },
        { name: 'drawStagger', label: 'Draw stagger', description: 'How much the letters are staggered in time, for Trace and Both ends (rebuilds)', type: 'number', min: 0, max: 0.95, step: 0.01 },
        { name: 'drawAngle', label: 'Draw direction', description: 'Direction of the sweep, for Wipe (rebuilds)', type: 'number', min: -180, max: 180, step: 1, unit: '°' },
        { name: 'eraseMethod', label: 'Erase', description: 'How the text disappears when it is switched off (rebuilds)', type: 'select', options: ['sublimate', 'fade', 'undraw', 'wipe', 'radial', 'scatter', 'dissolve', 'trace', 'bothEnds', 'pen', 'cut', 'none'], optionLabels: ['Sublimate', 'Fade', 'Reverse', 'Wipe', 'Radial', 'Scatter', 'Dissolve', 'Trace', 'Both ends', 'Pen', 'Cut', 'Off'] },
        { name: 'eraseDuration', label: 'Erase duration', description: 'How long the erase animation takes', type: 'number', min: 0.2, max: 15, step: 0.05, unit: 's' },
        { name: 'eraseEase', label: 'Erase easing', description: 'Easing of the erase animation', type: 'select', options: ['easeInOut', 'linear', 'easeOut', 'easeIn'], optionLabels: ['Smooth', 'Linear', 'Out', 'In'] },
        { name: 'eraseStagger', label: 'Erase stagger', description: 'How much the letters are staggered in time, for Trace and Both ends (rebuilds)', type: 'number', min: 0, max: 0.95, step: 0.01 },
        { name: 'eraseAngle', label: 'Erase direction', description: 'Direction of the sweep, for Wipe (rebuilds)', type: 'number', min: -180, max: 180, step: 1, unit: '°' },
        { name: 'autoPlay', label: 'Play on load', description: 'Play the draw animation when the scene starts', type: 'boolean' },
        { name: 'loop', label: 'Loop', description: 'Repeat hidden, draw, hold, erase, hidden', type: 'boolean' },
        { name: 'yoyo', label: 'Yoyo', description: 'Play the whole cycle forward, then backward', type: 'boolean' },
        { name: 'holdTime', label: 'Hold', description: 'How long the finished text stays before it is erased (loop)', type: 'number', min: 0, max: 10, step: 0.1, unit: 's' },
        { name: 'hiddenTime', label: 'Hidden pause', description: 'Pause with nothing shown between cycles (loop)', type: 'number', min: 0, max: 5, step: 0.1, unit: 's' },
    ],
    plasmaDischarge: [
        { name: 'branches', label: 'Branching', description: 'How many streamers fork off the letters', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'reach', label: 'Reach', description: 'How far the streamers reach from the letters', type: 'number', min: 0.05, max: 1, step: 0.01 },
        { name: 'branchiness', label: 'Branchiness', description: 'Low: straight streamers that follow the field closely. High: wandering, bushy, more forks', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'glow', label: 'Glow', description: 'Brightness and size of the plasma halo', type: 'number', min: 0, max: 2, step: 0.01 },
        { name: 'pulse', label: 'Current pulses', description: 'Strength of the current pulses travelling along the channels', type: 'number', min: 0, max: 1.5, step: 0.01 },
        { name: 'spectrum', label: 'Emission lines', description: 'Orange-red atomic-line tinge in the hottest channel and the faint recombination afterglow', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'core', label: 'Core width', description: 'Thickness of the white-hot arc core', type: 'number', min: 0.002, max: 0.02, step: 0.0005 },
        { name: 'color', label: 'Plasma', description: 'Colour of the plasma halo and cooling channels', type: 'color' },
        { name: 'color2', label: 'Hot core', description: 'Colour of the hottest, freshly struck channel', type: 'color' },
        { name: 'opacity', label: 'Opacity', description: 'Overall opacity', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'seed', label: 'Seed', description: 'Different streamer layout', type: 'number', min: 0, max: 99, step: 1 },
        { name: 'text', label: 'Text', description: 'The words; a new line starts a second line', type: 'string' },
        { name: 'font', label: 'Font', description: 'Typeface of the text (every look uses the same fonts)', type: 'select', options: ['inter', 'roboto', 'montserrat', 'poppins', 'oswald', 'bebas-neue', 'playfair-display', 'lora', 'caveat', 'kalam', 'handlee', 'patrick-hand', 'architects-daughter', 'indie-flower', 'gochi-hand', 'nanum-pen-script', 'mynerve', 'dancing-script', 'courgette', 'satisfy', 'kaushan-script', 'sriracha', 'pacifico'], optionLabels: ['Inter', 'Roboto', 'Montserrat', 'Poppins', 'Oswald', 'Bebas Neue', 'Playfair Display', 'Lora', 'Caveat', 'Kalam', 'Handlee', 'Patrick Hand', 'Architect\'s Daughter', 'Indie Flower', 'Gochi Hand', 'Nanum Pen', 'Mynerve', 'Dancing Script', 'Courgette', 'Satisfy', 'Kaushan Script', 'Sriracha', 'Pacifico'] },
        { name: 'drawMethod', label: 'Draw', description: 'How the text appears when it is shown (rebuilds)', type: 'select', options: ['strike', 'pen', 'trace', 'bothEnds', 'wipe', 'radial', 'scatter', 'dissolve', 'fade', 'none'], optionLabels: ['Strike', 'Pen', 'Trace', 'Both ends', 'Wipe', 'Radial', 'Scatter', 'Dissolve', 'Fade', 'Off'] },
        { name: 'drawDuration', label: 'Draw duration', description: 'How long the draw animation takes', type: 'number', min: 0.2, max: 15, step: 0.05, unit: 's' },
        { name: 'drawEase', label: 'Draw easing', description: 'Easing of the draw animation', type: 'select', options: ['easeInOut', 'linear', 'easeOut', 'easeIn'], optionLabels: ['Smooth', 'Linear', 'Out', 'In'] },
        { name: 'drawStagger', label: 'Draw stagger', description: 'How much the letters are staggered in time, for Trace and Both ends (rebuilds)', type: 'number', min: 0, max: 0.95, step: 0.01 },
        { name: 'drawAngle', label: 'Draw direction', description: 'Direction of the sweep, for Wipe (rebuilds)', type: 'number', min: -180, max: 180, step: 1, unit: '°' },
        { name: 'eraseMethod', label: 'Erase', description: 'How the text disappears when it is switched off (rebuilds)', type: 'select', options: ['fade', 'undraw', 'wipe', 'radial', 'scatter', 'dissolve', 'trace', 'bothEnds', 'pen', 'cut', 'none'], optionLabels: ['Fade', 'Reverse', 'Wipe', 'Radial', 'Scatter', 'Dissolve', 'Trace', 'Both ends', 'Pen', 'Cut', 'Off'] },
        { name: 'eraseDuration', label: 'Erase duration', description: 'How long the erase animation takes', type: 'number', min: 0.2, max: 15, step: 0.05, unit: 's' },
        { name: 'eraseEase', label: 'Erase easing', description: 'Easing of the erase animation', type: 'select', options: ['easeInOut', 'linear', 'easeOut', 'easeIn'], optionLabels: ['Smooth', 'Linear', 'Out', 'In'] },
        { name: 'eraseStagger', label: 'Erase stagger', description: 'How much the letters are staggered in time, for Trace and Both ends (rebuilds)', type: 'number', min: 0, max: 0.95, step: 0.01 },
        { name: 'eraseAngle', label: 'Erase direction', description: 'Direction of the sweep, for Wipe (rebuilds)', type: 'number', min: -180, max: 180, step: 1, unit: '°' },
        { name: 'autoPlay', label: 'Play on load', description: 'Play the draw animation when the scene starts', type: 'boolean' },
        { name: 'loop', label: 'Loop', description: 'Repeat hidden, draw, hold, erase, hidden', type: 'boolean' },
        { name: 'yoyo', label: 'Yoyo', description: 'Play the whole cycle forward, then backward', type: 'boolean' },
        { name: 'holdTime', label: 'Hold', description: 'How long the finished text stays before it is erased (loop)', type: 'number', min: 0, max: 10, step: 0.1, unit: 's' },
        { name: 'hiddenTime', label: 'Hidden pause', description: 'Pause with nothing shown between cycles (loop)', type: 'number', min: 0, max: 5, step: 0.1, unit: 's' },
    ],
    burnAway: [
        { name: 'char', label: 'Char', description: 'How much cracked char and ash is left behind the fire (0 = clean burn).', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'spread', label: 'Spread', description: 'Speed of the fire front; faster fronts leave their remains lingering longer.', type: 'number', min: 0.3, max: 2.2, step: 0.01 },
        { name: 'ember', label: 'Ember', description: 'Brightness and size of the embers, sparks and the glowing front.', type: 'number', min: 0, max: 2, step: 0.01 },
        { name: 'color', label: 'Paper', description: 'Colour of the paper.', type: 'color' },
        { name: 'color2', label: 'Ember colour', description: 'Hue of the glowing embers (tints the blackbody ramp).', type: 'color' },
        { name: 'roughness', label: 'Raggedness', description: 'How unevenly the fire spreads and how ragged the front is.', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'singe', label: 'Singe', description: 'Width and depth of the scorched brown rim at rest.', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'ashLace', label: 'Ash lace', description: 'How much of the writing stays as a fragile ash skeleton before it flakes away.', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'curl', label: 'Curl', description: 'How strongly the charring paper edge curls up toward the viewer.', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'opacity', label: 'Opacity', description: 'Overall opacity.', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'seed', label: 'Seed', description: 'Where the fire starts and how it spreads.', type: 'number', min: 0, max: 99, step: 1 },
        { name: 'text', label: 'Text', description: 'The words; a new line starts a second line', type: 'string' },
        { name: 'font', label: 'Font', description: 'Typeface of the text (every look uses the same fonts)', type: 'select', options: ['inter', 'roboto', 'montserrat', 'poppins', 'oswald', 'bebas-neue', 'playfair-display', 'lora', 'caveat', 'kalam', 'handlee', 'patrick-hand', 'architects-daughter', 'indie-flower', 'gochi-hand', 'nanum-pen-script', 'mynerve', 'dancing-script', 'courgette', 'satisfy', 'kaushan-script', 'sriracha', 'pacifico'], optionLabels: ['Inter', 'Roboto', 'Montserrat', 'Poppins', 'Oswald', 'Bebas Neue', 'Playfair Display', 'Lora', 'Caveat', 'Kalam', 'Handlee', 'Patrick Hand', 'Architect\'s Daughter', 'Indie Flower', 'Gochi Hand', 'Nanum Pen', 'Mynerve', 'Dancing Script', 'Courgette', 'Satisfy', 'Kaushan Script', 'Sriracha', 'Pacifico'] },
        { name: 'drawMethod', label: 'Draw', description: 'How the text appears when it is shown (rebuilds)', type: 'select', options: ['pen', 'trace', 'bothEnds', 'wipe', 'radial', 'scatter', 'dissolve', 'fade', 'none'], optionLabels: ['Pen', 'Trace', 'Both ends', 'Wipe', 'Radial', 'Scatter', 'Dissolve', 'Fade', 'Off'] },
        { name: 'drawDuration', label: 'Draw duration', description: 'How long the draw animation takes', type: 'number', min: 0.2, max: 15, step: 0.05, unit: 's' },
        { name: 'drawEase', label: 'Draw easing', description: 'Easing of the draw animation', type: 'select', options: ['easeInOut', 'linear', 'easeOut', 'easeIn'], optionLabels: ['Smooth', 'Linear', 'Out', 'In'] },
        { name: 'drawStagger', label: 'Draw stagger', description: 'How much the letters are staggered in time, for Trace and Both ends (rebuilds)', type: 'number', min: 0, max: 0.95, step: 0.01 },
        { name: 'drawAngle', label: 'Draw direction', description: 'Direction of the sweep, for Wipe (rebuilds)', type: 'number', min: -180, max: 180, step: 1, unit: '°' },
        { name: 'eraseMethod', label: 'Erase', description: 'How the text disappears when it is switched off (rebuilds)', type: 'select', options: ['burn', 'fade', 'undraw', 'wipe', 'radial', 'scatter', 'dissolve', 'trace', 'bothEnds', 'pen', 'cut', 'none'], optionLabels: ['Burn', 'Fade', 'Reverse', 'Wipe', 'Radial', 'Scatter', 'Dissolve', 'Trace', 'Both ends', 'Pen', 'Cut', 'Off'] },
        { name: 'eraseDuration', label: 'Erase duration', description: 'How long the erase animation takes', type: 'number', min: 0.2, max: 15, step: 0.05, unit: 's' },
        { name: 'eraseEase', label: 'Erase easing', description: 'Easing of the erase animation', type: 'select', options: ['easeInOut', 'linear', 'easeOut', 'easeIn'], optionLabels: ['Smooth', 'Linear', 'Out', 'In'] },
        { name: 'eraseStagger', label: 'Erase stagger', description: 'How much the letters are staggered in time, for Trace and Both ends (rebuilds)', type: 'number', min: 0, max: 0.95, step: 0.01 },
        { name: 'eraseAngle', label: 'Erase direction', description: 'Direction of the sweep, for Wipe (rebuilds)', type: 'number', min: -180, max: 180, step: 1, unit: '°' },
        { name: 'autoPlay', label: 'Play on load', description: 'Play the draw animation when the scene starts', type: 'boolean' },
        { name: 'loop', label: 'Loop', description: 'Repeat hidden, draw, hold, erase, hidden', type: 'boolean' },
        { name: 'yoyo', label: 'Yoyo', description: 'Play the whole cycle forward, then backward', type: 'boolean' },
        { name: 'holdTime', label: 'Hold', description: 'How long the finished text stays before it is erased (loop)', type: 'number', min: 0, max: 10, step: 0.1, unit: 's' },
        { name: 'hiddenTime', label: 'Hidden pause', description: 'Pause with nothing shown between cycles (loop)', type: 'number', min: 0, max: 5, step: 0.1, unit: 's' },
    ],
    lightPainting: [
        { name: 'exposure', label: 'Exposure', description: 'How long the shutter stayed open: trail brightness, bleaching towards white and persistence.', type: 'number', min: 0.2, max: 2.5, step: 0.01 },
        { name: 'temperature', label: 'Temperature', description: 'Colour temperature of the light source: low is ember red, high is cold white. Fresh trail is hotter and cools to this.', type: 'number', min: 1200, max: 9000, step: 10, unit: 'K' },
        { name: 'strobe', label: 'Strobe', description: 'The light pulses while writing: the trail becomes dots whose spacing shows pen speed (dense where slow). 0 is continuous.', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'sparks', label: 'Sparks', description: 'Sparkler mode: sparks thrown per second by the pen tip while writing. 0 is a plain LED torch.', type: 'number', min: 0, max: 400, step: 1, unit: '/s' },
        { name: 'width', label: 'Trail width', description: 'Width of the light trail (the source image on the sensor).', type: 'number', min: 0.004, max: 0.03, step: 0.0005, unit: 'em' },
        { name: 'halation', label: 'Halation', description: 'Film halation: a wide dim red-orange glow bleeding around the brightest exposure.', type: 'number', min: 0, max: 2, step: 0.01 },
        { name: 'tremor', label: 'Hand tremor', description: 'Physiological 8-12 Hz tremor of the hand: a faint fine ripple on the lines, smaller where the pen is slow.', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'spread', label: 'Spread', description: 'How violently the sparks are thrown out; low sparks drip, high sparks fan out wide.', type: 'number', min: 0, max: 1.6, step: 0.01 },
        { name: 'bloom', label: 'Bloom', description: 'Lens bloom and thin streak cross on the glowing pen tip.', type: 'number', min: 0, max: 2, step: 0.01 },
        { name: 'color', label: 'Colour', description: 'Resting colour of the trail (gel over the source), balanced by the temperature.', type: 'color' },
        { name: 'color2', label: 'Hot core', description: 'Colour of the fresh, hot trail and the tip.', type: 'color' },
        { name: 'opacity', label: 'Opacity', description: 'Overall opacity of the light.', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'text', label: 'Text', description: 'The words; a new line starts a second line', type: 'string' },
        { name: 'font', label: 'Font', description: 'Typeface of the text (every look uses the same fonts)', type: 'select', options: ['inter', 'roboto', 'montserrat', 'poppins', 'oswald', 'bebas-neue', 'playfair-display', 'lora', 'caveat', 'kalam', 'handlee', 'patrick-hand', 'architects-daughter', 'indie-flower', 'gochi-hand', 'nanum-pen-script', 'mynerve', 'dancing-script', 'courgette', 'satisfy', 'kaushan-script', 'sriracha', 'pacifico'], optionLabels: ['Inter', 'Roboto', 'Montserrat', 'Poppins', 'Oswald', 'Bebas Neue', 'Playfair Display', 'Lora', 'Caveat', 'Kalam', 'Handlee', 'Patrick Hand', 'Architect\'s Daughter', 'Indie Flower', 'Gochi Hand', 'Nanum Pen', 'Mynerve', 'Dancing Script', 'Courgette', 'Satisfy', 'Kaushan Script', 'Sriracha', 'Pacifico'] },
        { name: 'drawMethod', label: 'Draw', description: 'How the text appears when it is shown (rebuilds)', type: 'select', options: ['pen', 'trace', 'bothEnds', 'wipe', 'radial', 'scatter', 'dissolve', 'fade', 'none'], optionLabels: ['Pen', 'Trace', 'Both ends', 'Wipe', 'Radial', 'Scatter', 'Dissolve', 'Fade', 'Off'] },
        { name: 'drawDuration', label: 'Draw duration', description: 'How long the draw animation takes', type: 'number', min: 0.2, max: 15, step: 0.05, unit: 's' },
        { name: 'drawEase', label: 'Draw easing', description: 'Easing of the draw animation', type: 'select', options: ['easeInOut', 'linear', 'easeOut', 'easeIn'], optionLabels: ['Smooth', 'Linear', 'Out', 'In'] },
        { name: 'drawStagger', label: 'Draw stagger', description: 'How much the letters are staggered in time, for Trace and Both ends (rebuilds)', type: 'number', min: 0, max: 0.95, step: 0.01 },
        { name: 'drawAngle', label: 'Draw direction', description: 'Direction of the sweep, for Wipe (rebuilds)', type: 'number', min: -180, max: 180, step: 1, unit: '°' },
        { name: 'eraseMethod', label: 'Erase', description: 'How the text disappears when it is switched off (rebuilds)', type: 'select', options: ['fade', 'undraw', 'wipe', 'radial', 'scatter', 'dissolve', 'trace', 'bothEnds', 'pen', 'cut', 'none'], optionLabels: ['Fade', 'Reverse', 'Wipe', 'Radial', 'Scatter', 'Dissolve', 'Trace', 'Both ends', 'Pen', 'Cut', 'Off'] },
        { name: 'eraseDuration', label: 'Erase duration', description: 'How long the erase animation takes', type: 'number', min: 0.2, max: 15, step: 0.05, unit: 's' },
        { name: 'eraseEase', label: 'Erase easing', description: 'Easing of the erase animation', type: 'select', options: ['easeInOut', 'linear', 'easeOut', 'easeIn'], optionLabels: ['Smooth', 'Linear', 'Out', 'In'] },
        { name: 'eraseStagger', label: 'Erase stagger', description: 'How much the letters are staggered in time, for Trace and Both ends (rebuilds)', type: 'number', min: 0, max: 0.95, step: 0.01 },
        { name: 'eraseAngle', label: 'Erase direction', description: 'Direction of the sweep, for Wipe (rebuilds)', type: 'number', min: -180, max: 180, step: 1, unit: '°' },
        { name: 'autoPlay', label: 'Play on load', description: 'Play the draw animation when the scene starts', type: 'boolean' },
        { name: 'loop', label: 'Loop', description: 'Repeat hidden, draw, hold, erase, hidden', type: 'boolean' },
        { name: 'yoyo', label: 'Yoyo', description: 'Play the whole cycle forward, then backward', type: 'boolean' },
        { name: 'holdTime', label: 'Hold', description: 'How long the finished text stays before it is erased (loop)', type: 'number', min: 0, max: 10, step: 0.1, unit: 's' },
        { name: 'hiddenTime', label: 'Hidden pause', description: 'Pause with nothing shown between cycles (loop)', type: 'number', min: 0, max: 5, step: 0.1, unit: 's' },
    ],
    constellation: [
        { name: 'stars', label: 'Stars', description: 'Stars per em of pen stroke (density along the figure)', type: 'number', min: 3, max: 16, step: 0.5, unit: '/em' },
        { name: 'brightness', label: 'Brightness', description: 'Limiting magnitude shift: brighter, larger stars and more of the faint dust show', type: 'number', min: -1.5, max: 1.5, step: 0.05, unit: 'mag' },
        { name: 'temperature', label: 'Temperature', description: 'Shifts the whole star population cooler (amber) or hotter (blue-white)', type: 'number', min: -1, max: 1, step: 0.02 },
        { name: 'lines', label: 'Chart lines', description: 'Visibility of the lines joining the stars', type: 'number', min: 0, max: 1.5, step: 0.02 },
        { name: 'twinkle', label: 'Twinkle', description: 'Scintillation strength (0 = steady stars)', type: 'number', min: 0, max: 2, step: 0.02 },
        { name: 'color', label: 'Line colour', description: 'Colour of the chart lines', type: 'color' },
        { name: 'color2', label: 'Highlight / tint', description: 'Pulse highlight on the lines and a soft tint on the stars', type: 'color' },
        { name: 'opacity', label: 'Opacity', description: 'Overall opacity', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'seed', label: 'Seed', description: 'Which sky: star positions, magnitudes and colours', type: 'number', min: 0, max: 999, step: 1 },
        { name: 'text', label: 'Text', description: 'The words; a new line starts a second line', type: 'string' },
        { name: 'font', label: 'Font', description: 'Typeface of the text (every look uses the same fonts)', type: 'select', options: ['inter', 'roboto', 'montserrat', 'poppins', 'oswald', 'bebas-neue', 'playfair-display', 'lora', 'caveat', 'kalam', 'handlee', 'patrick-hand', 'architects-daughter', 'indie-flower', 'gochi-hand', 'nanum-pen-script', 'mynerve', 'dancing-script', 'courgette', 'satisfy', 'kaushan-script', 'sriracha', 'pacifico'], optionLabels: ['Inter', 'Roboto', 'Montserrat', 'Poppins', 'Oswald', 'Bebas Neue', 'Playfair Display', 'Lora', 'Caveat', 'Kalam', 'Handlee', 'Patrick Hand', 'Architect\'s Daughter', 'Indie Flower', 'Gochi Hand', 'Nanum Pen', 'Mynerve', 'Dancing Script', 'Courgette', 'Satisfy', 'Kaushan Script', 'Sriracha', 'Pacifico'] },
        { name: 'drawMethod', label: 'Draw', description: 'How the text appears when it is shown (rebuilds)', type: 'select', options: ['pen', 'trace', 'bothEnds', 'wipe', 'radial', 'scatter', 'dissolve', 'fade', 'none'], optionLabels: ['Pen', 'Trace', 'Both ends', 'Wipe', 'Radial', 'Scatter', 'Dissolve', 'Fade', 'Off'] },
        { name: 'drawDuration', label: 'Draw duration', description: 'How long the draw animation takes', type: 'number', min: 0.2, max: 15, step: 0.05, unit: 's' },
        { name: 'drawEase', label: 'Draw easing', description: 'Easing of the draw animation', type: 'select', options: ['easeInOut', 'linear', 'easeOut', 'easeIn'], optionLabels: ['Smooth', 'Linear', 'Out', 'In'] },
        { name: 'drawStagger', label: 'Draw stagger', description: 'How much the letters are staggered in time, for Trace and Both ends (rebuilds)', type: 'number', min: 0, max: 0.95, step: 0.01 },
        { name: 'drawAngle', label: 'Draw direction', description: 'Direction of the sweep, for Wipe (rebuilds)', type: 'number', min: -180, max: 180, step: 1, unit: '°' },
        { name: 'eraseMethod', label: 'Erase', description: 'How the text disappears when it is switched off (rebuilds)', type: 'select', options: ['fade', 'undraw', 'wipe', 'radial', 'scatter', 'dissolve', 'trace', 'bothEnds', 'pen', 'cut', 'none'], optionLabels: ['Fade', 'Reverse', 'Wipe', 'Radial', 'Scatter', 'Dissolve', 'Trace', 'Both ends', 'Pen', 'Cut', 'Off'] },
        { name: 'eraseDuration', label: 'Erase duration', description: 'How long the erase animation takes', type: 'number', min: 0.2, max: 15, step: 0.05, unit: 's' },
        { name: 'eraseEase', label: 'Erase easing', description: 'Easing of the erase animation', type: 'select', options: ['easeInOut', 'linear', 'easeOut', 'easeIn'], optionLabels: ['Smooth', 'Linear', 'Out', 'In'] },
        { name: 'eraseStagger', label: 'Erase stagger', description: 'How much the letters are staggered in time, for Trace and Both ends (rebuilds)', type: 'number', min: 0, max: 0.95, step: 0.01 },
        { name: 'eraseAngle', label: 'Erase direction', description: 'Direction of the sweep, for Wipe (rebuilds)', type: 'number', min: -180, max: 180, step: 1, unit: '°' },
        { name: 'autoPlay', label: 'Play on load', description: 'Play the draw animation when the scene starts', type: 'boolean' },
        { name: 'loop', label: 'Loop', description: 'Repeat hidden, draw, hold, erase, hidden', type: 'boolean' },
        { name: 'yoyo', label: 'Yoyo', description: 'Play the whole cycle forward, then backward', type: 'boolean' },
        { name: 'holdTime', label: 'Hold', description: 'How long the finished text stays before it is erased (loop)', type: 'number', min: 0, max: 10, step: 0.1, unit: 's' },
        { name: 'hiddenTime', label: 'Hidden pause', description: 'Pause with nothing shown between cycles (loop)', type: 'number', min: 0, max: 5, step: 0.1, unit: 's' },
    ],
    inkBleed: [
        { name: 'bleed', label: 'Bleed', description: 'How far the ink feathers into the paper', type: 'number', min: 0, max: 0.12, step: 0.002, unit: 'em' },
        { name: 'color', label: 'Ink', description: 'Colour of the dense dye (the dark core)', type: 'color' },
        { name: 'weight', label: 'Pen weight', description: 'Thickness of the pen line', type: 'number', min: 0.3, max: 1.6, step: 0.01 },
        { name: 'paper', label: 'Paper', description: '0 = ink only, 1 = a sheet of paper behind the text', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'color2', label: 'Fringe dye', description: 'Colour of the lighter dye that separates into the halo', type: 'color' },
        { name: 'dryTime', label: 'Drying time', description: 'How long the ink keeps wicking before it dries', type: 'number', min: 0.3, max: 8, step: 0.05, unit: 's' },
        { name: 'fibre', label: 'Fibre', description: 'How strongly the paper fibres guide and rag the feathering', type: 'number', min: 0, max: 1.5, step: 0.01 },
        { name: 'pooling', label: 'Pooling', description: 'Dark rim where the ink collects as it dries', type: 'number', min: 0, max: 1.5, step: 0.01 },
        { name: 'oxidation', label: 'Oxidation', description: 'Seconds the ink takes to darken from pale blue-grey to its final colour (iron-gall oxidation)', type: 'number', min: 0.3, max: 20, step: 0.1, unit: 's' },
        { name: 'burn', label: 'Ink burn', description: 'Slow browning of the paper around the lines, strongest where the pen pressed hard', type: 'number', min: 0, max: 1.5, step: 0.01 },
        { name: 'char', label: 'Char', description: 'How much cracked char and ash the fire leaves behind (0 = clean burn); used by the Burn erase', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'spread', label: 'Spread', description: 'Speed of the fire front; faster fronts leave their remains lingering longer (Burn erase)', type: 'number', min: 0.3, max: 2.2, step: 0.01 },
        { name: 'opacity', label: 'Opacity', description: 'Overall opacity', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'text', label: 'Text', description: 'The words; a new line starts a second line', type: 'string' },
        { name: 'font', label: 'Font', description: 'Typeface of the text (every look uses the same fonts)', type: 'select', options: ['inter', 'roboto', 'montserrat', 'poppins', 'oswald', 'bebas-neue', 'playfair-display', 'lora', 'caveat', 'kalam', 'handlee', 'patrick-hand', 'architects-daughter', 'indie-flower', 'gochi-hand', 'nanum-pen-script', 'mynerve', 'dancing-script', 'courgette', 'satisfy', 'kaushan-script', 'sriracha', 'pacifico'], optionLabels: ['Inter', 'Roboto', 'Montserrat', 'Poppins', 'Oswald', 'Bebas Neue', 'Playfair Display', 'Lora', 'Caveat', 'Kalam', 'Handlee', 'Patrick Hand', 'Architect\'s Daughter', 'Indie Flower', 'Gochi Hand', 'Nanum Pen', 'Mynerve', 'Dancing Script', 'Courgette', 'Satisfy', 'Kaushan Script', 'Sriracha', 'Pacifico'] },
        { name: 'drawMethod', label: 'Draw', description: 'How the text appears when it is shown (rebuilds)', type: 'select', options: ['pen', 'trace', 'bothEnds', 'wipe', 'radial', 'scatter', 'dissolve', 'fade', 'none'], optionLabels: ['Pen', 'Trace', 'Both ends', 'Wipe', 'Radial', 'Scatter', 'Dissolve', 'Fade', 'Off'] },
        { name: 'drawDuration', label: 'Draw duration', description: 'How long the draw animation takes', type: 'number', min: 0.2, max: 15, step: 0.05, unit: 's' },
        { name: 'drawEase', label: 'Draw easing', description: 'Easing of the draw animation', type: 'select', options: ['easeInOut', 'linear', 'easeOut', 'easeIn'], optionLabels: ['Smooth', 'Linear', 'Out', 'In'] },
        { name: 'drawStagger', label: 'Draw stagger', description: 'How much the letters are staggered in time, for Trace and Both ends (rebuilds)', type: 'number', min: 0, max: 0.95, step: 0.01 },
        { name: 'drawAngle', label: 'Draw direction', description: 'Direction of the sweep, for Wipe (rebuilds)', type: 'number', min: -180, max: 180, step: 1, unit: '°' },
        { name: 'eraseMethod', label: 'Erase', description: 'How the text disappears when it is switched off (rebuilds)', type: 'select', options: ['burn', 'fade', 'undraw', 'wipe', 'radial', 'scatter', 'dissolve', 'trace', 'bothEnds', 'pen', 'cut', 'none'], optionLabels: ['Burn', 'Fade', 'Reverse', 'Wipe', 'Radial', 'Scatter', 'Dissolve', 'Trace', 'Both ends', 'Pen', 'Cut', 'Off'] },
        { name: 'eraseDuration', label: 'Erase duration', description: 'How long the erase animation takes', type: 'number', min: 0.2, max: 15, step: 0.05, unit: 's' },
        { name: 'eraseEase', label: 'Erase easing', description: 'Easing of the erase animation', type: 'select', options: ['easeInOut', 'linear', 'easeOut', 'easeIn'], optionLabels: ['Smooth', 'Linear', 'Out', 'In'] },
        { name: 'eraseStagger', label: 'Erase stagger', description: 'How much the letters are staggered in time, for Trace and Both ends (rebuilds)', type: 'number', min: 0, max: 0.95, step: 0.01 },
        { name: 'eraseAngle', label: 'Erase direction', description: 'Direction of the sweep, for Wipe (rebuilds)', type: 'number', min: -180, max: 180, step: 1, unit: '°' },
        { name: 'autoPlay', label: 'Play on load', description: 'Play the draw animation when the scene starts', type: 'boolean' },
        { name: 'loop', label: 'Loop', description: 'Repeat hidden, draw, hold, erase, hidden', type: 'boolean' },
        { name: 'yoyo', label: 'Yoyo', description: 'Play the whole cycle forward, then backward', type: 'boolean' },
        { name: 'holdTime', label: 'Hold', description: 'How long the finished text stays before it is erased (loop)', type: 'number', min: 0, max: 10, step: 0.1, unit: 's' },
        { name: 'hiddenTime', label: 'Hidden pause', description: 'Pause with nothing shown between cycles (loop)', type: 'number', min: 0, max: 5, step: 0.1, unit: 's' },
    ],
    liquidMetal: [
        { name: 'thickness', label: 'Thickness', description: 'Puddle depth: the radius of the rounded meniscus at the rim of every letter.', type: 'number', min: 0.01, max: 0.2, step: 0.005, unit: 'em' },
        { name: 'environment', label: 'Environment', description: 'Contrast and brightness of the studio the metal mirrors.', type: 'number', min: 0.2, max: 1.5, step: 0.01 },
        { name: 'color', label: 'Metal colour', description: 'Colour of the metal at normal incidence (silver, gold, copper, blue-steel).', type: 'color' },
        { name: 'tint', label: 'Metal tint', description: 'How strongly the metal colours its reflection (0 = neutral chrome, 1 = full colour).', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'melt', label: 'Melt', description: 'Erase: how long the metal stays liquid and runs before it dewets (0 = dewets early, 1 = long liquid phase).', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'drips', label: 'Drips', description: 'Erase: density of gravity-fed rivulets and falling drops under the strokes.', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'spikes', label: 'Spikes', description: 'Magnetic field: the pool breaks into a hexagonal lattice of sharp cones (Rosensweig instability).', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'oxide', label: 'Oxide skin', description: 'Nanometre oxide film: thin-film interference tint and fine creases where the skin is compressed.', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'reflectivity', label: 'Reflectivity', description: 'Normal-incidence reflectance of the metal (mercury and chrome are ~0.6-0.9).', type: 'number', min: 0.3, max: 1, step: 0.01 },
        { name: 'roughness', label: 'Ripples', description: 'Amplitude of the surface swells and capillary ripples that tilt the mirror.', type: 'number', min: 0, max: 2, step: 0.01 },
        { name: 'rippleSpeed', label: 'Ripple speed', description: 'Speed of the travelling surface waves.', type: 'number', min: 0, max: 3, step: 0.01 },
        { name: 'color2', label: 'Edge tint', description: 'Colour of the reflection at grazing angles and on the rim.', type: 'color' },
        { name: 'opacity', label: 'Opacity', description: 'Overall opacity.', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'text', label: 'Text', description: 'The words; a new line starts a second line', type: 'string' },
        { name: 'font', label: 'Font', description: 'Typeface of the text (every look uses the same fonts)', type: 'select', options: ['inter', 'roboto', 'montserrat', 'poppins', 'oswald', 'bebas-neue', 'playfair-display', 'lora', 'caveat', 'kalam', 'handlee', 'patrick-hand', 'architects-daughter', 'indie-flower', 'gochi-hand', 'nanum-pen-script', 'mynerve', 'dancing-script', 'courgette', 'satisfy', 'kaushan-script', 'sriracha', 'pacifico'], optionLabels: ['Inter', 'Roboto', 'Montserrat', 'Poppins', 'Oswald', 'Bebas Neue', 'Playfair Display', 'Lora', 'Caveat', 'Kalam', 'Handlee', 'Patrick Hand', 'Architect\'s Daughter', 'Indie Flower', 'Gochi Hand', 'Nanum Pen', 'Mynerve', 'Dancing Script', 'Courgette', 'Satisfy', 'Kaushan Script', 'Sriracha', 'Pacifico'] },
        { name: 'drawMethod', label: 'Draw', description: 'How the text appears when it is shown (rebuilds)', type: 'select', options: ['flow', 'pen', 'trace', 'bothEnds', 'wipe', 'radial', 'scatter', 'dissolve', 'fade', 'none'], optionLabels: ['Flow', 'Pen', 'Trace', 'Both ends', 'Wipe', 'Radial', 'Scatter', 'Dissolve', 'Fade', 'Off'] },
        { name: 'drawDuration', label: 'Draw duration', description: 'How long the draw animation takes', type: 'number', min: 0.2, max: 15, step: 0.05, unit: 's' },
        { name: 'drawEase', label: 'Draw easing', description: 'Easing of the draw animation', type: 'select', options: ['easeInOut', 'linear', 'easeOut', 'easeIn'], optionLabels: ['Smooth', 'Linear', 'Out', 'In'] },
        { name: 'drawStagger', label: 'Draw stagger', description: 'How much the letters are staggered in time, for Trace and Both ends (rebuilds)', type: 'number', min: 0, max: 0.95, step: 0.01 },
        { name: 'drawAngle', label: 'Draw direction', description: 'Direction of the sweep, for Wipe (rebuilds)', type: 'number', min: -180, max: 180, step: 1, unit: '°' },
        { name: 'eraseMethod', label: 'Erase', description: 'How the text disappears when it is switched off (rebuilds)', type: 'select', options: ['melt', 'beads', 'fade', 'undraw', 'wipe', 'radial', 'scatter', 'dissolve', 'trace', 'bothEnds', 'pen', 'cut', 'none'], optionLabels: ['Melt', 'Beads', 'Fade', 'Reverse', 'Wipe', 'Radial', 'Scatter', 'Dissolve', 'Trace', 'Both ends', 'Pen', 'Cut', 'Off'] },
        { name: 'eraseDuration', label: 'Erase duration', description: 'How long the erase animation takes', type: 'number', min: 0.2, max: 15, step: 0.05, unit: 's' },
        { name: 'eraseEase', label: 'Erase easing', description: 'Easing of the erase animation', type: 'select', options: ['easeInOut', 'linear', 'easeOut', 'easeIn'], optionLabels: ['Smooth', 'Linear', 'Out', 'In'] },
        { name: 'eraseStagger', label: 'Erase stagger', description: 'How much the letters are staggered in time, for Trace and Both ends (rebuilds)', type: 'number', min: 0, max: 0.95, step: 0.01 },
        { name: 'eraseAngle', label: 'Erase direction', description: 'Direction of the sweep, for Wipe (rebuilds)', type: 'number', min: -180, max: 180, step: 1, unit: '°' },
        { name: 'autoPlay', label: 'Play on load', description: 'Play the draw animation when the scene starts', type: 'boolean' },
        { name: 'loop', label: 'Loop', description: 'Repeat hidden, draw, hold, erase, hidden', type: 'boolean' },
        { name: 'yoyo', label: 'Yoyo', description: 'Play the whole cycle forward, then backward', type: 'boolean' },
        { name: 'holdTime', label: 'Hold', description: 'How long the finished text stays before it is erased (loop)', type: 'number', min: 0, max: 10, step: 0.1, unit: 's' },
        { name: 'hiddenTime', label: 'Hidden pause', description: 'Pause with nothing shown between cycles (loop)', type: 'number', min: 0, max: 5, step: 0.1, unit: 's' },
    ],
    embroidery: [
        { name: 'color', label: 'Thread', description: 'Main satin thread colour', type: 'color' },
        { name: 'sheen', label: 'Sheen', description: 'Strength of the silk highlight that sweeps over the stitching', type: 'number', min: 0, max: 2, step: 0.01 },
        { name: 'density', label: 'Density', description: 'Stitches per em along the stroke', type: 'number', min: 14, max: 70, step: 1, unit: '/em' },
        { name: 'thickness', label: 'Thickness', description: 'Width of the satin column relative to the pen stroke', type: 'number', min: 0.6, max: 2.4, step: 0.01 },
        { name: 'color2', label: 'Contrast thread', description: 'Border running-stitch thread', type: 'color' },
        { name: 'relief', label: 'Relief', description: 'Raised look: thread height, groove shadows and stitch ends diving under neighbours', type: 'number', min: 0, max: 1.5, step: 0.01 },
        { name: 'outline', label: 'Border row', description: 'Visibility of the contrast running-stitch border', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'fabric', label: 'Fabric', description: 'Faint linen weave behind the stitching', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'pucker', label: 'Pucker', description: 'Dense stitching gathers the cloth: soft wrinkles around the stitching, deeper tight counters (fabric layer only)', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'style', label: 'Stitch style', description: 'Automatic picks per stroke: satin, stem stitch, couching, French knots. Or force one', type: 'select', options: ['auto', 'satin', 'stem', 'couching'], optionLabels: ['Automatic', 'Satin', 'Stem', 'Couching'] },
        { name: 'slant', label: 'Slant', description: 'Satin stitch angle to the stroke direction', type: 'number', min: 40, max: 85, step: 1, unit: '°' },
        { name: 'opacity', label: 'Opacity', description: 'Overall opacity', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'text', label: 'Text', description: 'The words; a new line starts a second line', type: 'string' },
        { name: 'font', label: 'Font', description: 'Typeface of the text (every look uses the same fonts)', type: 'select', options: ['inter', 'roboto', 'montserrat', 'poppins', 'oswald', 'bebas-neue', 'playfair-display', 'lora', 'caveat', 'kalam', 'handlee', 'patrick-hand', 'architects-daughter', 'indie-flower', 'gochi-hand', 'nanum-pen-script', 'mynerve', 'dancing-script', 'courgette', 'satisfy', 'kaushan-script', 'sriracha', 'pacifico'], optionLabels: ['Inter', 'Roboto', 'Montserrat', 'Poppins', 'Oswald', 'Bebas Neue', 'Playfair Display', 'Lora', 'Caveat', 'Kalam', 'Handlee', 'Patrick Hand', 'Architect\'s Daughter', 'Indie Flower', 'Gochi Hand', 'Nanum Pen', 'Mynerve', 'Dancing Script', 'Courgette', 'Satisfy', 'Kaushan Script', 'Sriracha', 'Pacifico'] },
        { name: 'drawMethod', label: 'Draw', description: 'How the text appears when it is shown (rebuilds)', type: 'select', options: ['stitch', 'pen', 'trace', 'bothEnds', 'wipe', 'radial', 'scatter', 'dissolve', 'fade', 'none'], optionLabels: ['Stitch', 'Pen', 'Trace', 'Both ends', 'Wipe', 'Radial', 'Scatter', 'Dissolve', 'Fade', 'Off'] },
        { name: 'drawDuration', label: 'Draw duration', description: 'How long the draw animation takes', type: 'number', min: 0.2, max: 15, step: 0.05, unit: 's' },
        { name: 'drawEase', label: 'Draw easing', description: 'Easing of the draw animation', type: 'select', options: ['easeInOut', 'linear', 'easeOut', 'easeIn'], optionLabels: ['Smooth', 'Linear', 'Out', 'In'] },
        { name: 'drawStagger', label: 'Draw stagger', description: 'How much the letters are staggered in time, for Trace and Both ends (rebuilds)', type: 'number', min: 0, max: 0.95, step: 0.01 },
        { name: 'drawAngle', label: 'Draw direction', description: 'Direction of the sweep, for Wipe (rebuilds)', type: 'number', min: -180, max: 180, step: 1, unit: '°' },
        { name: 'eraseMethod', label: 'Erase', description: 'How the text disappears when it is switched off (rebuilds)', type: 'select', options: ['undraw', 'unpick', 'fade', 'wipe', 'radial', 'scatter', 'dissolve', 'trace', 'bothEnds', 'pen', 'cut', 'none'], optionLabels: ['Reverse', 'Unpick', 'Fade', 'Wipe', 'Radial', 'Scatter', 'Dissolve', 'Trace', 'Both ends', 'Pen', 'Cut', 'Off'] },
        { name: 'eraseDuration', label: 'Erase duration', description: 'How long the erase animation takes', type: 'number', min: 0.2, max: 15, step: 0.05, unit: 's' },
        { name: 'eraseEase', label: 'Erase easing', description: 'Easing of the erase animation', type: 'select', options: ['easeInOut', 'linear', 'easeOut', 'easeIn'], optionLabels: ['Smooth', 'Linear', 'Out', 'In'] },
        { name: 'eraseStagger', label: 'Erase stagger', description: 'How much the letters are staggered in time, for Trace and Both ends (rebuilds)', type: 'number', min: 0, max: 0.95, step: 0.01 },
        { name: 'eraseAngle', label: 'Erase direction', description: 'Direction of the sweep, for Wipe (rebuilds)', type: 'number', min: -180, max: 180, step: 1, unit: '°' },
        { name: 'autoPlay', label: 'Play on load', description: 'Play the draw animation when the scene starts', type: 'boolean' },
        { name: 'loop', label: 'Loop', description: 'Repeat hidden, draw, hold, erase, hidden', type: 'boolean' },
        { name: 'yoyo', label: 'Yoyo', description: 'Play the whole cycle forward, then backward', type: 'boolean' },
        { name: 'holdTime', label: 'Hold', description: 'How long the finished text stays before it is erased (loop)', type: 'number', min: 0, max: 10, step: 0.1, unit: 's' },
        { name: 'hiddenTime', label: 'Hidden pause', description: 'Pause with nothing shown between cycles (loop)', type: 'number', min: 0, max: 5, step: 0.1, unit: 's' },
    ],
    chalkboard: [
        { name: 'pressure', label: 'Pressure', description: 'How hard the chalk is pressed: light = broken grainy line, heavy = nearly solid', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'chatter', label: 'Chatter', description: 'Stick-slip skipping: fast, light strokes break into dashes whose spacing follows pen speed', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'grain', label: 'Grain', description: 'Contrast of the board relief the chalk catches on', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'dust', label: 'Dust', description: 'Falling chalk dust at the tip while writing', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'weight', label: 'Weight', description: 'Thickness of the chalk stick', type: 'number', min: 0.4, max: 2.5, step: 0.01 },
        { name: 'swing', label: 'Swing', description: 'Curvature of the felt swipe: 0 = straight band, 1 = tight arc about the elbow', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'ghost', label: 'Ghost', description: 'Chalk residue left by the smudge erase before it fades out', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'board', label: 'Board', description: 'Slate board behind the text with faint old writing', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'opacity', label: 'Opacity', description: 'Overall opacity', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'color', label: 'Chalk', description: 'Chalk colour', type: 'color' },
        { name: 'color2', label: 'Highlight', description: 'Tint of the dense deposit', type: 'color' },
        { name: 'text', label: 'Text', description: 'The words; a new line starts a second line', type: 'string' },
        { name: 'font', label: 'Font', description: 'Typeface of the text (every look uses the same fonts)', type: 'select', options: ['inter', 'roboto', 'montserrat', 'poppins', 'oswald', 'bebas-neue', 'playfair-display', 'lora', 'caveat', 'kalam', 'handlee', 'patrick-hand', 'architects-daughter', 'indie-flower', 'gochi-hand', 'nanum-pen-script', 'mynerve', 'dancing-script', 'courgette', 'satisfy', 'kaushan-script', 'sriracha', 'pacifico'], optionLabels: ['Inter', 'Roboto', 'Montserrat', 'Poppins', 'Oswald', 'Bebas Neue', 'Playfair Display', 'Lora', 'Caveat', 'Kalam', 'Handlee', 'Patrick Hand', 'Architect\'s Daughter', 'Indie Flower', 'Gochi Hand', 'Nanum Pen', 'Mynerve', 'Dancing Script', 'Courgette', 'Satisfy', 'Kaushan Script', 'Sriracha', 'Pacifico'] },
        { name: 'drawMethod', label: 'Draw', description: 'How the text appears when it is shown (rebuilds)', type: 'select', options: ['pen', 'trace', 'bothEnds', 'wipe', 'radial', 'scatter', 'dissolve', 'fade', 'none'], optionLabels: ['Pen', 'Trace', 'Both ends', 'Wipe', 'Radial', 'Scatter', 'Dissolve', 'Fade', 'Off'] },
        { name: 'drawDuration', label: 'Draw duration', description: 'How long the draw animation takes', type: 'number', min: 0.2, max: 15, step: 0.05, unit: 's' },
        { name: 'drawEase', label: 'Draw easing', description: 'Easing of the draw animation', type: 'select', options: ['easeInOut', 'linear', 'easeOut', 'easeIn'], optionLabels: ['Smooth', 'Linear', 'Out', 'In'] },
        { name: 'drawStagger', label: 'Draw stagger', description: 'How much the letters are staggered in time, for Trace and Both ends (rebuilds)', type: 'number', min: 0, max: 0.95, step: 0.01 },
        { name: 'drawAngle', label: 'Draw direction', description: 'Direction of the sweep, for Wipe (rebuilds)', type: 'number', min: -180, max: 180, step: 1, unit: '°' },
        { name: 'eraseMethod', label: 'Erase', description: 'How the text disappears when it is switched off (rebuilds)', type: 'select', options: ['smudge', 'fade', 'undraw', 'wipe', 'radial', 'scatter', 'dissolve', 'trace', 'bothEnds', 'pen', 'cut', 'none'], optionLabels: ['Smudge', 'Fade', 'Reverse', 'Wipe', 'Radial', 'Scatter', 'Dissolve', 'Trace', 'Both ends', 'Pen', 'Cut', 'Off'] },
        { name: 'eraseDuration', label: 'Erase duration', description: 'How long the erase animation takes', type: 'number', min: 0.2, max: 15, step: 0.05, unit: 's' },
        { name: 'eraseEase', label: 'Erase easing', description: 'Easing of the erase animation', type: 'select', options: ['easeInOut', 'linear', 'easeOut', 'easeIn'], optionLabels: ['Smooth', 'Linear', 'Out', 'In'] },
        { name: 'eraseStagger', label: 'Erase stagger', description: 'How much the letters are staggered in time, for Trace and Both ends (rebuilds)', type: 'number', min: 0, max: 0.95, step: 0.01 },
        { name: 'eraseAngle', label: 'Erase direction', description: 'Direction of the sweep, for Wipe (rebuilds)', type: 'number', min: -180, max: 180, step: 1, unit: '°' },
        { name: 'autoPlay', label: 'Play on load', description: 'Play the draw animation when the scene starts', type: 'boolean' },
        { name: 'loop', label: 'Loop', description: 'Repeat hidden, draw, hold, erase, hidden', type: 'boolean' },
        { name: 'yoyo', label: 'Yoyo', description: 'Play the whole cycle forward, then backward', type: 'boolean' },
        { name: 'holdTime', label: 'Hold', description: 'How long the finished text stays before it is erased (loop)', type: 'number', min: 0, max: 10, step: 0.1, unit: 's' },
        { name: 'hiddenTime', label: 'Hidden pause', description: 'Pause with nothing shown between cycles (loop)', type: 'number', min: 0, max: 5, step: 0.1, unit: 's' },
    ],
    plain: [
        { name: 'color', label: 'Colour', description: 'Colour of the face', type: 'color' },
        { name: 'weight', label: 'Weight', description: 'Bolder (right) or lighter (left) face: offsets every edge of the letters', type: 'number', min: -0.04, max: 0.05, step: 0.001, unit: 'em' },
        { name: 'outline', label: 'Outline', description: 'Width of the outline drawn just outside the face (0 = none)', type: 'number', min: 0, max: 0.08, step: 0.001, unit: 'em' },
        { name: 'opacity', label: 'Opacity', description: 'Overall opacity', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'color2', label: 'Outline colour', description: 'Colour of the outline', type: 'color' },
        { name: 'fill', label: 'Fill', description: 'Opacity of the face alone (0 with an outline = hollow letters)', type: 'number', min: 0, max: 1, step: 0.01 },
        { name: 'softness', label: 'Softness', description: 'Width of the edge transition: 0 is crisp, more is a soft printed edge', type: 'number', min: 0, max: 0.06, step: 0.001, unit: 'em' },
        { name: 'text', label: 'Text', description: 'The words; a new line starts a second line', type: 'string' },
        { name: 'font', label: 'Font', description: 'Typeface of the text (every look uses the same fonts)', type: 'select', options: ['inter', 'roboto', 'montserrat', 'poppins', 'oswald', 'bebas-neue', 'playfair-display', 'lora', 'caveat', 'kalam', 'handlee', 'patrick-hand', 'architects-daughter', 'indie-flower', 'gochi-hand', 'nanum-pen-script', 'mynerve', 'dancing-script', 'courgette', 'satisfy', 'kaushan-script', 'sriracha', 'pacifico'], optionLabels: ['Inter', 'Roboto', 'Montserrat', 'Poppins', 'Oswald', 'Bebas Neue', 'Playfair Display', 'Lora', 'Caveat', 'Kalam', 'Handlee', 'Patrick Hand', 'Architect\'s Daughter', 'Indie Flower', 'Gochi Hand', 'Nanum Pen', 'Mynerve', 'Dancing Script', 'Courgette', 'Satisfy', 'Kaushan Script', 'Sriracha', 'Pacifico'] },
        { name: 'drawMethod', label: 'Draw', description: 'How the text appears when it is shown (rebuilds)', type: 'select', options: ['pen', 'trace', 'bothEnds', 'wipe', 'radial', 'scatter', 'dissolve', 'fade', 'none'], optionLabels: ['Pen', 'Trace', 'Both ends', 'Wipe', 'Radial', 'Scatter', 'Dissolve', 'Fade', 'Off'] },
        { name: 'drawDuration', label: 'Draw duration', description: 'How long the draw animation takes', type: 'number', min: 0.2, max: 15, step: 0.05, unit: 's' },
        { name: 'drawEase', label: 'Draw easing', description: 'Easing of the draw animation', type: 'select', options: ['easeInOut', 'linear', 'easeOut', 'easeIn'], optionLabels: ['Smooth', 'Linear', 'Out', 'In'] },
        { name: 'drawStagger', label: 'Draw stagger', description: 'How much the letters are staggered in time, for Trace and Both ends (rebuilds)', type: 'number', min: 0, max: 0.95, step: 0.01 },
        { name: 'drawAngle', label: 'Draw direction', description: 'Direction of the sweep, for Wipe (rebuilds)', type: 'number', min: -180, max: 180, step: 1, unit: '°' },
        { name: 'eraseMethod', label: 'Erase', description: 'How the text disappears when it is switched off (rebuilds)', type: 'select', options: ['fade', 'undraw', 'wipe', 'radial', 'scatter', 'dissolve', 'trace', 'bothEnds', 'pen', 'cut', 'none'], optionLabels: ['Fade', 'Reverse', 'Wipe', 'Radial', 'Scatter', 'Dissolve', 'Trace', 'Both ends', 'Pen', 'Cut', 'Off'] },
        { name: 'eraseDuration', label: 'Erase duration', description: 'How long the erase animation takes', type: 'number', min: 0.2, max: 15, step: 0.05, unit: 's' },
        { name: 'eraseEase', label: 'Erase easing', description: 'Easing of the erase animation', type: 'select', options: ['easeInOut', 'linear', 'easeOut', 'easeIn'], optionLabels: ['Smooth', 'Linear', 'Out', 'In'] },
        { name: 'eraseStagger', label: 'Erase stagger', description: 'How much the letters are staggered in time, for Trace and Both ends (rebuilds)', type: 'number', min: 0, max: 0.95, step: 0.01 },
        { name: 'eraseAngle', label: 'Erase direction', description: 'Direction of the sweep, for Wipe (rebuilds)', type: 'number', min: -180, max: 180, step: 1, unit: '°' },
        { name: 'autoPlay', label: 'Play on load', description: 'Play the draw animation when the scene starts', type: 'boolean' },
        { name: 'loop', label: 'Loop', description: 'Repeat hidden, draw, hold, erase, hidden', type: 'boolean' },
        { name: 'yoyo', label: 'Yoyo', description: 'Play the whole cycle forward, then backward', type: 'boolean' },
        { name: 'holdTime', label: 'Hold', description: 'How long the finished text stays before it is erased (loop)', type: 'number', min: 0, max: 10, step: 0.1, unit: 's' },
        { name: 'hiddenTime', label: 'Hidden pause', description: 'Pause with nothing shown between cycles (loop)', type: 'number', min: 0, max: 5, step: 0.1, unit: 's' },
    ],
};
